---
pagetitle: lab-meetings
---

# Lab Meetings

For the Spring 2023 Semester, we will meet on Thursdays 8:00-8:50am in room 350 Moore.

## Previous meeting notes

[Notes from previous semesters](lab-meetings-previous.html)

## Helpful Links

- Global Protect Instructions for [Mac](https://ithelp.ssri.psu.edu/penn-state-vpn-mac) and [Windows ](https://ithelp.ssri.psu.edu/penn-state-vpn)
- Click to login to our [R Studio Server space](https://rstudio.tlt.psu.edu/s/e40b8122db8f5ab27456f/)
- Click to login to [Datacamp](https://www.datacamp.com/)
- How to take screen shots for [Mac](https://support.apple.com/en-us/HT201361) and [Windows](https://www.howtogeek.com/226280/how-to-take-screenshots-in-windows-10/)
- [Databrary](https://www.databrary.org)

## Goals
- Data science
    - Learn R on [Datacamp](https://www.datacamp.com/)
    - Begin by creating or updating your a brief biography for the [Who we are](https://gilmore-lab.github.io/who-we-are.html) page on the lab website.
- Start preparing for presentations in the Spring
    - Train on poster template for R [posterdown](https://github.com/brentthorne/posterdown)
    - Train how to use Databrary API
<!-- - Launch new projects -->
<!--     - [Development of Motion Sensitivity Meta-analysis](https://github.com/gilmore-lab/motion-metaanalysis) -->
<!--     - Visuomotor tracking -->
- Data Processing/Analysis projects
    - Databrary Tagging
    - Databrary User Guide
    - Open Science Survey Data
    - Datavyu Coding of infant locomotion??
- Submit abstracts for poster presentation:
  - [Undergraduate Research Exhibition](https://urfm.psu.edu/programs/undergraduate-exhibition#paragraphs-id-114)
  - [Psi Chi Research Conference](https://sites.psu.edu/psichi/research-conference-2/)
- Future readings:
  - Yiming's PhD paper and paper reviews

[Psych 494 Syllabus](https://gilmore-lab.github.io/protocols/psych-494-syllabus.html) 

## Spring 2023

### 5/4/2023 Lab Breakfast @ Waffle Shop 

### 4/27/2023 350 Moore
- Attending: Rick, Andrea, Cecelia, Belle, Madison, Oriana, Yiming
  - Excused: Kayla
  - Absent: Molly, Bowen, Ysa
- Discuss
  - How relevant is Rmarkdown in other classes? not so much, but maybe in the future
  
  - protocols book
    - Create instructions for: Github, data camp, rstudio and some other missing sections
    - fix image size and box formatting
  - should we switch to outlook calendar or stay with google calendar
  - most don't use teams so stay with Discord
  - look at [Play Project Surveys](https://play-behaviorome.github.io/KoBoToolbox/visualizations.html)
  
- To Do:
  - ARS - create Datacamp plan for lab next semester and add to lab meeting agendas
  

### 4/20/2023 NO MEETING

### 4/13/2023 350 Moore
- Attending: Rick, Andrea, Kayla, Bowen, Cecelia, Belle, Madison, Oriana, Yiming, Ysa
  - Excused: Kavya, Melody
  - Absent: Molly
  
- Discuss:
  - How to create a new project on Git and clone repository in RStudio
  - Next Project is Visual Acuity - Teller Acuity Cards
  - Work on setting up Bookdown for Visual Acuity project
  - easier to copy from another repository and alter them for new project
    - need files: _bookdown.yml, _output.yml, and index.Rmd
    - set up files and directories in visual-acuity-project folder
    - generate book
    - set up webpage 
  
### 4/6/2023 350 Moore
- Attending: Rick, Andrea, Yiming, Kayla, Bowen, Alex
  - Excused: Molly, Oriana, Madison, Kavya, Belle, Cecelia, Melody
  - Absent: Ysa

- Discuss:
  - [Ham Radio Book](https://k3cr.github.io/newhambook/)
    - Alex tested some of the activities in chapter 3 Hands on Hamming.
  - Motion Sensitivity Paper Study
    - What is development of infants visual acuity - Teller Acuity Cards
    - Create database/metaanalysis/data aggregation of Teller Acuity Card results over time
    
  - [Open Science Bootcamp 2023 Book](https://penn-state-open-science.github.io/bootcamp-2023/)
- Homework:
  - ARS: Find Teller Acuity Card info for Gilmore Lab
  - ARS: Schedule final meeting
  - Look up "Teller Acuity Cards" if you have time.
  
- Next Week:
  - Live literature search
  - work on protocol
  
  
### 3/30/2023 350 Moore
- Attending: Rick, Andrea, Yiming, Oriana, Cecilia, Belle, Madison, Belle, Molly
  - Excused: Kayla, Kavya, Melody
  - Absent: Ysa

- Discuss:
  - Tips and Tricks for R on http://gilmore-lab.github.io/protocols/tricks-and-tips.html
  - Tester for Annual Compliance Training began evaluation 
  
- Protocols Project 
  - on Github: https://github.com/gilmore-lab/protocols
  - live site: http://gilmore-lab.github.io/protocols/

- Homework:
  - Belle - complete evaluation of Annual Compliance Training began evaluation 

- Project Teams:
  - Bowen, Madison, Belle: Annual Compliance Training
  - Oriana, Yiming, Cecilia, Molly: CITI Training
  
### 3/23/2023 350 Moore
- Attending: Rick, Andrea, Kayla, Madison, Belle, Cecilia, Melody, Bowen, Yiming
  - Excused: Oriana, Kavya, Ysa
  - Absent: Molly
  
- Discuss: 
  - Best way to merge work from multiple people - we think push to master
  - how to show a code chunk without running code

- Homework:
  - ARS - add link to location in book down that shows how to show code chunk
  - change global options for saving  -ARS emailed ROG
  
  - Everyone keep working on sections for protocols. Push changes to master branch

### 3/16/2023 350 Moore
- Attending: Rick, Madison, Oriana, Kayla, Belle, Cecilia
  - Absent: Ysa, Kavya
  - Excused: Andrea, Yiming, Bowen

- Discuss:

- Homework: 


### 3/9/2023 Spring Break

### 3/2/2023 CANCELLED

### 2/23/2023

- Attending: Rick, Andrea, Yiming, Oriana, Madison, Bowen, Cecilia
  - Absent: Molly, Ysa, Kavya
  - Excused: Belle

- Discuss:
   - Does everyone have R and R Studio Installed? YES :)
   - Edit: Protocols repository in R Studio
      - take off numbering of headers by adding ` {-}` at the end of each header
      - function takes an input and produces an output. Anything that is given to the function is in parentheses `()` while things that we are looking at are in square brackets `[]`. 

- Homework:   
  - Everyone pull the protocols repo locally to your R Studio.
  - Think about and update (if possible) pages with screenshots and descriptive text/links
      - CITI training: Oriana, Cecilia, Yiming
      - Yearly Compliance Training: Madison, Kayla, Bowen
   
### 2/16/2023

- Attending: Rick, Andrea, Molly, Kayla, Madison, Belle, Cecilia, Bowen, Oriana
  - Absent Ysa, Kavya  

- Discuss:  
  - all but 1 have R and R Studio Installed  
  - Everyone has GitHub Accounts  
  - issue with syncing with GitHub error: "Support for password authentication was removed. Please use a personal access token instead."  

- Install Github  

  - for mac:  
  https://www.freecodecamp.org/news/setup-git-on-mac/  
  `cmd + space` and type `terminal` to open  
  run command at prompt $ xcode-select --install  
  
  - for windows:  
  https://git-scm.com/download/win  
  choose the correct version for your computer and run the installer  
  
- Connect R with GitHub  

  - Read Chapter 9: https://happygitwithr.com/https-pat.html and try to do this at home  
  - When R and GitHub are connected


- Clone Repository  

  - go to github website

- In RStudio 

  - Make Changes  
  - render the book using command > bookdown::render_book()  
  - Save  
  - commit  
  - Push once synchronization or R and Git is working  

- Homework:  
  - create documentation for synchronization R and Git ARS/Rick/Melody  
  - Outstanding Training on Asana: Molly and Kayla  
  
  
  
### 2/9/2023

- Attending: Rick, Andrea, Molly, Kayla, Madison, Belle, Cecilia, Bowen, Oriana, Yiming, Melody
  - Absent: Ysa, Kavya

- Discuss:  
  - Work session: bookdown site for all lab protocols
    - Anatomy of using Bookdown files  
      - `.gitignore`: don't keep track of the files in this file  
      - `protocols.Rproj`: this file has information project information specific to your computer  
      - `.Rhistory`: history of your files that you have run recently  
      - folders for resources
        - `imgs/` (eg. jpg, )
        - `pdfs/`
        - `docs/` rendered documents
      `index.Rmd`: 
      - `README.md`: this a descriptive file for how to use this repository
      anything within a back tick (\`)  will appear like `this`
   `.yml` YAML (yet another markup language)
      - renv.lock explains the files required to run in the renv/ folder
      
    - render book: 
    - chunk of code is in between three back ticks (```)
    
{whatLanguage chunkLabel, paramaters}   
   package::command(paramaters)    

   

- Homework:
  - Complete any training assigned via Asana
  - What theme do we want for bookdown? bookdown:: bs4_book is used currently

### 2/2/2023

- Attending: Molly, Kayla, Belle, Madison, Cecilia, Oriana, Yiming, Rick, Andrea, Melody, Bowen
   - Absent: Ysa, Kavya

- Discuss:
   - Introductions: Melody joined the meeting for the first time
   - Projects: Create Databrary User Guide [Git](https://github.com/databrary/guide) and Lab Protocols Manual [Git](https://github.com/gilmore-lab/protocols) using Github/RStudio/bookdown
   - Lab Protocols Manual
   - Everyone needs GitHub Accounts
   
   - [Undergraduate Research Jumpstart Program](https://www.psu.edu/news/university-libraries/story/libraries-undergraduate-research-jumpstart-program-seeks-participants/?utm_audience=Combined&utm_source=newswire&utm_medium=email&utm_campaign=Penn%20State%20Today&utm_content=01-31-2023-20-59&utm_term=Announcements%20-%203) - Share with your friends who may be interested in research, but not sure where to start
   - Chapters 1 and 2 of [Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)

- Homework: Complete any outstanding Training. Check Asana!


### 1/26/2023

- Attending: Rick, Andrea, Bowen, Kayla, Belle, Cecilia, Madison, Oriana, Yiming
  - Excused: Ysa, Molly
  - Kavya
- Discuss:
  - What is R and RStudio?
  - What is [Bookdown](https://bookdown.org/)?
  - [Penn State Open Science](https://github.com/penn-state-open-science/roadmap)
    - complete IRB protocol
    - [PLAY Behaviorome](https://play-behaviorome.github.io./protocol/)
      - how to run the study
      - recruitment data for entire PLAY project to date

- Homework:
  - Read Chapters 1 and 2 of [Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
  - Check Asana Tasks Weekly
  - The following students have training to take or retake:
      - Oriana
      - Bowen
      - Kayla
      - Ysa
      
- Next Week:
  - Begin to create a bookdown site for all lab protocols
  - review syllabus and goals above
  - Research ethics
  - Databrary and reproducibility crisis

### 1/19/2023

- Attending: Rick, Andrea, Yiming, Molly, Bowen, Kayla, Ysa, Belle, Cecilia, Oriana, Madison
  - Excused: Kavya
- Discuss: 
  - Introductions 
  - Yiming - present 15 min job talk
    - provide feedback on slides and talk
- Homework:
  - Work on any training assigned via Asana. We will discuss next week if there are any problems.
