---
pagetitle: lab-meetings-previous
---

# Past Lab Meetings

---

## Spring 2022

### 3/30/2022
  
- Attending: Rick, Andrea, Yiming, Molly, Maggie, Kavya, Kayla, Belle, Shahir, Lakshmi
  - Excused: Anjali
  - Missing: Kym   
  
  
- Discuss: Silberzahn, R., Uhlmann, E. L., Martin, D. P., Anselmi, P., Aust, F., Awtrey, E., Bahník, Š., Bai, F., Bannard, C., Bonnier, E., Carlsson, R., Cheung, F., Christensen, G., Clay, R., Craig, M. A., Dalla Rosa, A., Dam, L., Evans, M. H., Flores Cervantes, I., … Nosek, B. A. (2018). Many analysts, one data set: Making transparent how variations in analytic choices affect results. Advances in Methods and Practices in Psychological Science, 1(3), 337–356. https://doi.org/10.1177/2515245917747646

- Homework:
  - Complete any outstanding items you have on ASANA.   

### 3/23/2022 Meeting Cancelled

Homework:

- Read: Silberzahn, R., Uhlmann, E. L., Martin, D. P., Anselmi, P., Aust, F., Awtrey, E., Bahník, Š., Bai, F., Bannard, C., Bonnier, E., Carlsson, R., Cheung, F., Christensen, G., Clay, R., Craig, M. A., Dalla Rosa, A., Dam, L., Evans, M. H., Flores Cervantes, I., … Nosek, B. A. (2018). Many analysts, one data set: Making transparent how variations in analytic choices affect results. Advances in Methods and Practices in Psychological Science, 1(3), 337–356. https://doi.org/10.1177/2515245917747646

- Complete any outstanding items you have on ASANA. Everyone check as some training certificates have recently expired.

- Email the 3 courses you will take on [Datacamp](https://www.datacamp.com/) BEFORE the end of semester to psubrainlab@gmail.com so they can be assigned to you  

### 3/9/2022 Enjoy your Spring Break!

### 3/2/2022
  
- Attending: Rick, Andrea, Yiming, Molly, Maggie, Kavya, Anjali, Belle, Shahir, Lakshmi
  - Missing: Kayla, Kym  
  
- Agenda:
  - Discuss reading reproducibility papers over the next few weeks. Here is the schedule:
    - Discuss on 3/16/2022: Errington, T. M., Mathur, M., Soderberg, C. K., Denis, A., Perfito, N., Iorns, E., & Nosek, B. A. (2021). Investigating the replicability of preclinical cancer biology. eLife, 10, e71601. https://doi.org/10.7554/eLife.71601
    - Discuss on 3/23/2022: Open Science Collaboration. (2015). Estimating the reproducibility of psychological science. Science, 349(6251), aac4716. https://doi.org/10.1126/science.aac4716
    - Discuss on 3/30/2022: Camerer, C. F., Dreber, A., Holzmeister, F., Ho, T.-H., Huber, J., Johannesson, M., Kirchler, M., Nave, G., Nosek, B. A., Pfeiffer, T., Altmejd, A., Buttrick, N., Chan, T., Chen, Y., Forsell, E., Gampa, A., Heikensten, E., Hummer, L., Imai, T., … Wu, H. (2018). Evaluating the replicability of social science experiments in Nature and Science between 2010 and 2015. Nature Human Behaviour, 1. https://doi.org/10.1038/s41562-018-0399-z
    - Discuss on 4/6/2022: Silberzahn, R., Uhlmann, E. L., Martin, D. P., Anselmi, P., Aust, F., Awtrey, E., Bahník, Š., Bai, F., Bannard, C., Bonnier, E., Carlsson, R., Cheung, F., Christensen, G., Clay, R., Craig, M. A., Dalla Rosa, A., Dam, L., Evans, M. H., Flores Cervantes, I., … Nosek, B. A. (2018). Many analysts, one data set: Making transparent how variations in analytic choices affect results. Advances in Methods and Practices in Psychological Science, 1(3), 337–356. https://doi.org/10.1177/2515245917747646  
    
- Homework: Due 3/16/2022
    - Read: Errington, T. M., Mathur, M., Soderberg, C. K., Denis, A., Perfito, N., Iorns, E., & Nosek, B. A. (2021). Investigating the replicability of preclinical cancer biology. eLife, 10, e71601. https://doi.org/10.7554/eLife.71601
    - Complete any outstanding items you have on ASANA. Everyone check as some training certificates have recently expired.
    - Email the 3 courses you will take on [Datacamp](https://www.datacamp.com/) BEFORE the end of semester to psubrainlab@gmail.com so they can be assigned to you  
  

### 2/23/2022
- Attending: Rick, Andrea, Yiming, Molly, Anjali, Kayla, Belle,Lakshmi
  - Excused: Bowen, Kavya, Shahir
  - Missing: Maggie, Kym

- Agenda: Begin [Data Science for Everyone](https://campus.datacamp.com/courses/data-science-for-everyone/introduction-to-data-science-1?ex=1) as a group 

### 2/16/2022
- Attending: Rick, Andrea, Yiming, Molly, Maggie, Kavya, Anjali, Kayla, Belle, Shahir, Lakshmi, Kym

- Agenda: Short meeting, gift of time due to many exams and THON

### 2/9/2022
- Attending: Rick, Andrea, Yiming, Molly, Maggie, Kavya, Anjali, Kayla, Belle, Shahir, Lakshmi, Kym

- Agenda:
  - Remember to check discord at least twice a week, Mondays and fridays
  - remember to pick 3 courses on datacamp
  - overview of [Dryad](https://datadryad.org/)

- Homework:
  - Review [Dryad](https://datadryad.org/)
    - Note items such as: business model/funding, technical abilities, data curation services, how many staff members, what are the data about, file types (e.g., text, video, MRI, EEG), what is included in the data description.
  - Find one dataset on this repository that you may be interested in learning more about 
  - Log into Asana to see if you have any outstanding assignments. 
  - Reminder: Completion of assignments, attendance and participation at meetings are all part of determining your grade for the semester. The requirements are the same if you are a volunteer.

- Next Meeting
  - we will download one of the datasets on Dryad and look at it in detail 


### 2/2/2022
- Attending: Rick, Andrea, Yiming, Molly, Maggie, Kavya, Anjali, Kayla, Belle, Shahir, Lakshmi, Kym
  - Excused: Bowen

- Agenda:
  - Discuss:
    - Lab Website [(Meeting Notes)](https://gilmore-lab.github.io/lab-meetings.html)
    - Gilmore Lab Group [GitHub](https://github.com/gilmore-lab) Repository
    - using R Studio to update the lab website
   
- Homework:
  - Create [Github](https://github.com/) account and send username to discord channel
  - Write or update your [biography](https://gilmore-lab.github.io/who-we-are.html) make sure to use at least one link formatted for R (e.g. I work in the `[Gilmore Lab](https://gilmore-lab.github.io/)` at Penn State.). Send completed biography to the [Lab Email](psubrainlab@gmail.com)
  - pick 3 courses in Datacamp and send to Andrea via discord
  - Global Protect (instructions in 'Helpful Computer Information' above) needs to be run when off campus BEFORE logging into R Studio Server - Install this if you don't have it already
  - Create account/log on to TLT [R Studio Server](https://lat.tlt.psu.edu/home/remoteaccess/oss-web-apps/) - link mid page
    
  - Check out data repositories.  
    - [Scholarsphere](https://scholarsphere.psu.edu/)
    - [Dataverse](https://dataverse.org/)
    - [ICPSR](https://www.icpsr.umich.edu/web/pages/)
  - Outstanding Training: All instructions are on Asana
    - Molly: Reporting Child Abuse, Compliance Training, Title IX, Create GitHub account, Create Biography
    - Anjali: Compliance Training, Title IX
    - Shahir: Clery Act, Reporting Child Abuse
    - Lakshmi: Compliance Training, Title IX
    - Kym: Create Biography

### 1/26/2022


- Attending: Rick, Andrea, Yiming, Molly, Maggie, Bowen, Kavya, Anjali, Kayla, Belle, Shahir, Lakshmi, Kym
  - Missing: Sara
  
- Agenda:
  - Discuss: Soska, K. C., Xu, M., Gonzalez, S. L., Herzberg, O., Tamis-LeMonda, C. S., Gilmore, R. O., & Adolph, K. E. (2021). (Hyper)active data curation: A video case study from behavioral science. Journal of Escience Librarianship, 10(3). https://doi.org/10.7191/jeslib.2021.1208
    - PLAY about transparently publishing the process 
    - consistent naming schemes 
    - KoBoToolbox - moves files around and gathers files from video, survey, and decibel
    
- Notes:
  - Meeting notes will be kept [here](https://gilmore-lab.github.io/lab-meetings.html)
  - Communication is Key!
    - Discord is used in between meetings
    - send a note here if you will miss a meeting.

- To Do:
  - Accept the invite sent to your PSU account to join the class on Datacamp.
  - Log in, Pick 3 [R courses on Datacamp](https://app.datacamp.com/learn/courses?technologies=R) to complete by the end of the semester, and send the list of courses to me via Discord
    - Take `Introduction to R` and `Intermediate R` before taking anything else.
  - Asana Tasks:
    - Training
    - Write or update your [biography](https://gilmore-lab.github.io/who-we-are.html) make sure to use at least one link formatted for R (e.g. I work in the `[Gilmore Lab](https://gilmore-lab.github.io/)` at Penn State.)


### 1/19/2022

- Attending: Rick, Andrea, Yiming, Molly, Maggie, Bowen, Kavya, Anjali, Kayla, Belle, Shahir, Lakshmi
  - Missing: Sara, Kym
- Agenda
  - Introduction of lab members
  - discuss PLAY

- To Do:
  - Training Assigned in Asana
  - Join Discord
  - Read: Soska, K. C., Xu, M., Gonzalez, S. L., Herzberg, O., Tamis-LeMonda, C. S., Gilmore, R. O., & Adolph, K. E. (2021). (Hyper)active data curation: A video case study from behavioral science. Journal of Escience Librarianship, 10(3). https://doi.org/10.7191/jeslib.2021.1208 

## Fall 2021

### November 24, 2021

HAPPY THANKSGIVING!

- To Do:
  - Training: All instructions are on Asana
    - Sara: Clery Act, Reporting Child Abuse
    - Bowen: Compliance Training
    - Anjali: Compliance Training, Title IX
    
### November 17, 2021 (Zoom)

- Attending: Andrea, Rick, Anjali, Belle, Bowen, Kavya, Kayla, Sara, Shahir, Yiming, Kym
  - Absent: Maggie

- Agenda: 
  - Discuss: Zwaan, R. A., Etz, A., Lucas, R. E., & Donnellan, M. B. (2017). Making replication mainstream. The Behavioral and Brain Sciences, 41, e120. https://doi.org/10.1017/S0140525X17001972
  
- To Do:
  - Training: All instructions are on Asana
    - Sara: Clery Act, Reporting Child Abuse
    - Bowen: Compliance Training
    - Anjali: Compliance Training, Title IX
    

### November 10, 2021 (Zoom)

- Attending: Andrea, Rick, Anjali, Belle, Bowen, Kavya, Kayla, Maggie, Sara, Shahir, Yiming
  - Excused: Kym

- Agenda:
  - import databrary-volume-survey and begin R coding report
    - create table coder vs # files
    - need - number of volumes
  - second pass
    - all of the investigators_1 = volume_owner - create a row for each investigator for private volumes only - ARS

- To Do:
  - Training: All instructions are on Asana
    - Yiming: Clery Act, Reporting Child Abuse, Compliance Training, Title IX
    - Sara: Clery Act, Reporting Child Abuse
    - Bowen: Compliance Training
    - Anjali: Compliance Training, Title IX
    - Kym: CITI Training, Compliance Training, Title IX
    
### November 3, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Iris, Anjali, Kavya, Kayla, Maggie, Shahir, Belle, Kym  
  - Missing: Sara

- Agenda:  
  - What kind of volume analysis:
    - #files vs. sharing level
    - title quality vs. sharing level
  - Grant proposal - what do research participants understand about where their data is going to go, what do they want to happen to their data

- To Do:
  - add your name/initials to git hub repository if it isn't already there
  - finish phase I of Databrary volume survey
  - think about contexts in which you provide data
  - Training: All instructions are on Asana
    - Yiming: Clery Act, Reporting Child Abuse, Compliance Training, Title IX
    - Maggie: Clery Act, Reporting Child Abuse, Compliance Training, Title IX
    - Sara: Clery Act, Reporting Child Abuse
    - Iris: Compliance Training
    - Anjali: Compliance Training, Title IX
    - Kayla: Clery Act, Reporting Child Abuse
    - Kym: CITI Training, Compliance Training, Title IX
    
- Next Week:
  - look at Databrary volume survey dataset
  - discuss papers

### October 27, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Sara, Iris, Anjali, Kavya, Kayla, Maggie, Shahir, Belle  

- Agenda:
  - Detailed Discussion of project looking at Databrary Volume
    - why is this important
    - create a protocol for any project
    - update protocol in R 
    - initial R skeleton for generating tables/graphs of data
      - Github repo: https://github.com/gilmore-lab/databrary-volume-survey
  - All training up to date for: Belle, Shahir, Kavya, Andrea
- To Do:    
  - All lab members    
    - Log into Asana. Complete ALL training by 11/3/2021. 
    - Complete volume coding for up to Volume 1000 by next week.

### October 20, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Sara, Iris, Anjali, Kavya, Kayla, Kym, Maggie, Shahir, Belle  

- Agenda:
  - Detailed Discussion of project looking at Databrary Volumes and the information provided.
      - Github repo: https://github.com/gilmore-lab/databrary-volume-survey
  - All training up to date for: Belle, Shahir, Kavya, Andrea
- To Do:    
  - All lab members    
    - Log into Asana. Complete ALL training by 10/27/2021. 
    - Complete volume coding for 10 volumes before next week.
  - ARS -  work out issues with Kayla Clery Act training. When they retake the training, the new training certificate and date do not appear.  
  
### October 13, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Anjali, Kayla, Kym, Kavya, Iris, Shahir, Belle  

- Agenda:
  - Begin discussing a project to review Databrary volume page details
  - Github repo: https://github.com/gilmore-lab/databrary-volume-survey
  
- To Do:    
  - All lab members    
    - Create Databrary Accounts and request Authorization from Rick O. Gilmore    
    - Log into Asana. Make sure assigned training gets completed.  
  - ARS -  work out issues with Kayla Clery Act training. When they retake the training, the new training certificate and date do not appear.  
  
    
### October 6, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Anjali, Kayla, Kym, Maggie, Shahir, Belle  

- Agenda:
  - Talk by Yiming Qian: Sex Differences in Motion Perception
  
- Next Week:  
  - Discuss project looking at Databrary Volumes and the information provided.
  
- To Do:    
  - All lab members    
    - Create Databrary Accounts and request Authorization from Rick O. Gilmore    
    - Log into Asana. Make sure assigned training gets completed.  
  - ARS -  work out issues with Kayla and Anjali Clery Act training. When they retake the training, the new training certificate and date do not appear.  
  

### September 28, 2021 (Zoom)

- Attending: Rick, Andrea, Iris, Anjali, Kavya, Kayla, Maggie, Shahir, Yiming, Kym, Sara

- Agenda:
  - Continue Discussing: Ossmy, O., Han, D., Kaplan, B. E., Xu, M., Bianco, C., Mukamel, R., & Adolph, K. E. (2021). Children do not distinguish efficient from inefficient actions during observation. Scientific Reports, 11(1), 18106. https://doi.org/10.1038/s41598-021-97354-9
  
- To Do: 
  - Log into Asana. Make sure assigned training gets completed.
  - Read: Sex Differences Paper - it will be shared via email and Discord

### September 22, 2021 (Zoom)

- Attending: Rick, Andrea, Iris, Anjali,Evan, Kavya, Kayla, Maggie, Shahir, Yiming

- Agenda:
  - Discuss: Ossmy, O., Han, D., Kaplan, B. E., Xu, M., Bianco, C., Mukamel, R., & Adolph, K. E. (2021). Children do not distinguish efficient from inefficient actions during observation. Scientific Reports, 11(1), 18106. https://doi.org/10.1038/s41598-021-97354-9
  
- To Do: Continue discussing this paper next week.

### September 15, 2021 (Zoom)

- Attending: Rick, Andrea, Iris, Anjali, Belle, Evan, Kavya, Kayla, Maggie, Shahir, Yiming

- Agenda:
  - Discuss: Gilmore, R.O., & Qian, Y. (2021). An open developmental science will be more rigorous, robust, and impactful. Infant and Child Development. https://doi.org/10.1002/icd.2254. 
  - Discuss Data sharing, access to journal articles, review of articles, fees of journals, 
 

- To Do:
  - Accept the invitation to join the lab Datacamp class
  - Finish updating Biographies
  - Complete assigned training
  - Read: Ossmy, O., Han, D., Kaplan, B. E., Xu, M., Bianco, C., Mukamel, R., & Adolph, K. E. (2021). Children do not distinguish efficient from inefficient actions during observation. Scientific Reports, 11(1), 18106. https://doi.org/10.1038/s41598-021-97354-9
  
### September 8, 2021 (Zoom)

CANCELLED
    
### September 1, 2021 (Zoom)

- Attending: Rick, Andrea, Sara, Iris, Anjali, Evan, Kayla, Belle, Shahir, Kavya
  
- Agenda:
  - Introduction of lab members
  - Review of current [Lab Projects](https://gilmore-lab.github.io/research.html)
  - Meeting notes will be kept [here](https://gilmore-lab.github.io/lab-meetings.html)
  
- To Do for next meeting:
  - Read: Gilmore, R.O., & Qian, Y. (2021). An open developmental science will be more rigorous, robust, and impactful. Infant and Child Development. https://doi.org/10.1002/icd.2254. 
  - Write: Create or update your biography for the [lab website](https://gilmore-lab.github.io/who-we-are.html). Instructions sent via Asana



## Spring 2021 Meeting schedule 

### April 16, 2021 (Zoom)
- Attending: Rick, Andrea, Yiming, Anjali, Anna, Kayla, Kym, Rachel, Shahir
  - Excused: Maggie, Sara
- Agenda:
  - Teams Discuss 
    - [Scholarsphere](https://scholarsphere.psu.edu/) (Anna, Shahir, Anjali discussed)
      - anyone can use it 
      - search bar is on the homepage 
      - way to manage and keep research works for the future
      - each thing has a #of views graph - like this
      - many types of works (articles, book, poster, papers, datasets, thesis, etc.)
      - click to view .pdf
      - work history available for each work (versioning)
      - How are Featured Works selected?
      - Some works are open access and some are PSU only (I assume would need to log in to access)
      - What Difference between Library website and Scholarsphere site?
      - nice clean interface
    - [Dataverse](https://dataverse.org/) (Maggie, Sara) 
    - [ICPSR](https://www.icpsr.umich.edu/web/pages/) (Kym and Rachel discussed)
      - Health and nutrition
      - Excercise sets for use in classrooms - really like this!
      - Users - Universities, Non profits, research institutions
      - Improve - not sure how to get the data, is membership needed?
      - pay annual subscription fee (PSU is a subscriber)
      - video introduction - likes this!
        - how to search for data
        - what is ICPSR?
        - Need - how to gain access
      - not student friendly - how to do use the site
  - Discuss paper and view different types of displays.

### April 13, 2021 - Tuesday Work Session
- Attending: Rick, Andrea, Shahir, Sara, Yiming, Anna, Sydney, Rachel
- Agenda:
  - Teams Discuss [Scholarsphere](https://scholarsphere.psu.edu/) (Anna, Shahir), [Dataverse](https://dataverse.org/) (Maggie, Sara), [ICPSR](https://www.icpsr.umich.edu/web/pages/) (Rachel)
  - Paper review - Yiming assigned papers
- To Do:
  - For Each Data repository give a tour and answer the following questions for Friday
    - Who is the audience? 
    - What kind of data and materials are stored there? 
    - Why is it important (or to whom)? 
    - Are there data here that you could imagine wanting to use for a project? Why or why not? 
    - Does the repository have features that seem really important for repositories in general?
    
### April 9, 2021 (Zoom)
- Attending: Andrea, Yiming, Anjali, Anna, Kayla, Kym, Rachel, Sara
  - Excused: Shahir
  - Absent: Maureen, Michelle
- Agenda:
  - Work Session - Independent paper reviews assigned by Yiming.
- To Do: 
  - Review Data Repositories
    - Shahir & Anjali : https://scholarsphere.psu.edu/
    - Rachel & Kim: https://www.icpsr.umich.edu/web/pages/
    - Maggie & Sara: https://dataverse.org/
  - Answer these questions:
    - Who is the audience? 
    - What kind of data and materials are stored there? 
    - Why is it important (or to whom)? 
    - Are there data here that you could imagine wanting to use for a project? Why or why not? 
    - Does the repository have features that seem really important for repositories in general?
  - Read this paper and be prepared to discuss on Friday April 16, 2021 
    - Hadad, B., Schwartz, S., Maurer, D., & Lewis, T. L. (2015). Motion perception: a review of developmental changes and the role of early visual experience. Frontiers in Integrative Neuroscience, 9, 49. https://doi.org/10.3389/fnint.2015.00049
    
### March 26, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Anjali, Anna, Kayla, Kym, Maureen, Rachel, Sara, Shahir  
- Agenda:
  - Review - Hobbies Visualization completed by Shahir
  - Yiming reviewed 2 papers that had conflicting responses in the paper meta-analysis
    - continue to dig through jargon
  - Options to access R
    - Install locally
    - Liberal Arts Site for accessing R? (Could not find reference to this-ARS)
    - Access from Computer lab on Campus
  
- To Do:
  - Everyone complete some type of hobbies visualization to begin utilizing R. These will be reviewed net week.

### March 19, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Anjali, Anna, Kayla, Kym, Maureen, Rachel, Sara, Shahir  
- Agenda  
  - Administrative - Anna and Sydney still cannot get Global Protect to work on her personal computer
  - Datacamp - people still working in initial R - ARS needs to assign Data Visualization
  - Motion Metaanalysis updates
    - most duplicate coding of papers match each other.     
    - current coding form: https://forms.gle/Qd9H49tpDVjCRnob9
    - update to protocol is needed - hand mark up document, scan then email to Yiming  
    - protocol creation gold standard (e.g. https://www.play-project.org/)
      - add instructions and/or screen shots for each field.
    - the current protocol (https://github.com/gilmore-lab/motion-metaanalysis/blob/master/protocol.Rmd) needs to be updated or rewritten
  - How to take screen shots
    - [Mac](https://support.apple.com/en-us/HT201361) (click for detailed instructions)
      - portion of screen - Press and hold **Shift + Command + 4**
      - whole screen - Press and hold **Shift + Command + 3** 
    - [Windows](https://www.howtogeek.com/226280/how-to-take-screenshots-in-windows-10/) (click for detailed instructions)
      - portion of screen - Press and hold **Windows + Shift + S**
      - only one window - Click on the title bar of the window that you want to capture. Press **Alt + PrtScn** or **Alt + Fn + PrtScn**
      - whole screen - Press **Windows logo key + PrtScn**
    - Screen shots are typically saved in 
  - Review a paper together
  - Shahir has updates to Rmd document for hobbies - discuss next wee at worksessions or weekly meeting.
  
### March 12, 2021

Enjoy a day off!

### March 4, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Anjali, Kym, Sara, Shahir, Anna, Maureen, Kayla
- Agenda
  - Discuss
    - Hobbies Data and updates made last week
      - notes in hobbies.Rmd
      - leave good instructions
    - Paper Coding
      
- To Do:
  - everyone pick a few hobbies to compare using the hobbies_visualization_template.Rmd
  - keep reading papers and categorizing them
  
    
### February 26, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Kym, Sara, Shahir, Anjali, Maureen, Michelle, Rachel, Kayla, Anna
- Agenda:
  - Updates 
    - Shahir - PDFs updated on paperpile and create protocol
    - Anjali - Update hobbies csv - M/F, major - ARS uploaded upated CSV
  - Discuss Paper coding - Yiming
    - Each person needs to be assigned a paper.
    - Use the [coding google form](https://forms.gle/Qd9H49tpDVjCRnob9) to complete the coding
    - Instructions for getting into paperpile are on Discord


### February 12, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Kym, Sara, Shahir, Anna, Maureen, Michelle, Rachel, Kayla
- Agenda
  - Discuss
    - Protocols (why do we document?, video protocol, IRB)
    - Hobbies Data
    
- To Do:
  - Read Lippa, R., & Connelly, S. (1990). Gender diagnosticity: A new Bayesian approach to gender-related individual differences. Journal of Personality and Social Psychology, 59(5), 1051–1065. https://doi.org/10.1037/0022-3514.59.5.1051 [PDF](docs/pdfs/psp_59_5_1051.pdf)

- Next Meeting:
  - Review the Sex Differences IRB protocol
    
### January 29, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Kym, Sara, Shahir, Anna, Maureen, Michelle, Rachel, Kayla
- Agenda
  - Sex Differences in Motion Perception 
    - Data Types Collected
      - Motion Duation Threshold: Staircase Task
      - Contrast Sensitivity: Staircase Task  
      - Survey Data (Mental Rotation, Hobbies, Vocabulary)
    - Data that we looked at today
      - (Exclude Outliers)[https://gilmore-lab.github.io/sex-differences-in-motion-perception/analysis/code_analysis_exoutliers.html]
      - (Contrast RT by Condition)[https://gilmore-lab.github.io/sex-differences-in-motion-perception/analysis/contrast-rt-by-cond-plots.html]
      - (Contrast RT by Trial)[https://gilmore-lab.github.io/sex-differences-in-motion-perception/analysis/contrast-rt-trials-plots.html]
      - Survey Data: (Hobbies)[https://gilmore-lab.github.io/sex-differences-in-motion-perception/analysis/hobbies.html] 
  - Project Options
    - Reaction Time (RT) Data (motion rt, contrast rt)
       - do males and females show RT tradoff (RT vs. motion duration)
       - are there sex differences in RT
    - Hobbies Data
      - Do survey data relate to one another and the visual tasks, what does it mean
    - Motion Meta Analysis
      - Review papers and categorize them. Yiming will discuss next week.
 - To do:
  - Think about data and which projects are interesting to you
  - Read Paper

  
      

  - Submit 1-2 projects to the Spring 2021 [Psi Chi](http://sites.psu.edu/psichi/) conference
        - [Application](http://sites.psu.edu/psichi/research-conference-2/) due March 15, 2021 by 5:00pm  
        - Conference will be held April 15, 2021
        - Do we have any submissions that were sent last year, but not presented?
- To Do

### January 22, 2021 (Zoom)

- Attending: Rick, Andrea, Yiming, Maureen, Anna, Rachel, Sara, Anjali,Michelle, Kayla, Shahir, Kymberle
  - Excused: Maureen
  - Separate Meeting time: Sydney
- Agenda
  - Introductions
  - Overview of projects this semester
  - Select one other 1 hour block for each student to participate in lab projects


## Fall 2020 Meeting schedule 

### 27 October 2020 (Zoom)

- Attending:
- Agenda
    - Discuss:
    
    

### 20 October 2020 (Zoom)

- Attending: Rick, Andrea, Maggie, Emily, YIming, Rachel, Kayla, Anna, Shahir, Sara, Anjali, Chelsea
- Agenda
    - Discuss: Bassett, D. S., Cullen, K. E., Eickhoff, S. B., Farah, M. J., Goda, Y., Haggard, P., Hu, H., Hurd, Y. L., Josselyn, S. A., Khakh, B. S., Knoblich, J. A., Poirazi, P., Poldrack, R. A., Prinz, M., Roelfsema, P. R., Spires-Jones, T. L., Sur, M., & Ueda, H. R. (2020). Reflections on the past two decades of neuroscience. Nature Reviews. Neuroscience, 21(10), 524–534. https://doi.org/10.1038/s41583-020-0363-6
- To Do: Read new paper for next week
    

### 13 October 2020 CANCELLED

### 6 October 2020 (Zoom)

- Attending: Rick, Andrea, Sara, Emily, Rachel, Yiming, Kayla, Anjali, Anna, Shahir
  - Excused/Sick: Chelsea, Maggie
- Agenda
    - Discuss R Awesomeness and Woes
      - Emily's code
      - lapply, strsplit
      - Yiming - Weibull_MLM code
      - .Rmd - allows you to combine R code, figures, text into one file
      
    

### 29 September 2020 (Zoom)

- Attending: Rick, Andrea, Chelsea, Kayla, Sara, Maggie, Rachel, Anna, Anjali, Shahir
  - Post Meeting: Michelle
- Agenda
  - Introduction to R Resources
    - [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
    - [DataCamp](https://learn.datacamp.com/) - log in using PSU email address
    
- To Do
    - Create GitHub account if you don't already have one, share name with ARS
    - Keep working on R
    - Bring to class: something that is cool that you learned OR something you are struggling with. We will screen share.

### 22 September 2020 (Zoom)

- Attending: Rick, Andrea, Yiming, Chelsea, Kayla, Sara, Maggie, Rachel, Anna, Anjali, Shahir
  - Excused: Emily
  - Post Meeting: Michelle
- Agenda
  - Discuss 
      - Mounoud, P., Viviani, P., Hauert, C. A., & Guyon, J. (1985). Development of visuomanual tracking in 5- to 9-year-old boys. Journal of Experimental Child Psychology, 40(1), 115–132. https://doi.org/10.1016/0022-0965(85)90068-2. [Annotatable PDF](pdfs/mounoud-etal-1985.pdf).
      - Review DataCamp courses, send email to Andrea about where you want to start (in R) and one other course
      - Review lab web site, and make at least one annotation or comment
- To Do
  - Work on your R Assignment on DataCamp.
      
### 15 September 2020 (Zoom)

- Attending: Rick, Andrea, Yiming, Maggie, Anna, Chelsea, Sara, Anjali, Kayla, Shahir
  - Post Meeting: Michelle, Emily Rachel
- Agenda 
  - Discuss Biographies
  - Communication Tools
      - Asana, Discord - Everyone Joined
      - Datacamp - join Psych 494 Research Studies Fall 2020 group space - Emily
      - Hypothes.is - join new gilmore-lab space. Link posted in Discord
  - Training Status Update
      - CITI - Maureen, Sara, Kayla, Shahir
      - Clery Act - Yiming, Sara, Emily, Kayla, Shahir
      - Reporting Child Abuse - Yiming, Sara, Emily, Anjali, Michelle, Kayla, Shahir
      - Two more trainings, Title IX and Annual Compliance Training will be assigned
  - To Do
      - Visuomanual tracking lit review, read and discuss next week: Mounoud, P., Viviani, P., Hauert, C. A., & Guyon, J. (1985). Development of visuomanual tracking in 5- to 9-year-old boys. Journal of Experimental Child Psychology, 40(1), 115–132. https://doi.org/10.1016/0022-0965(85)90068-2. 
          - *Who* (were the participants), *what* (did they do), *what* (was measured), *what* (was found), *why* (should we care), *what* (does it mean)
      - Review DataCamp courses, send email to Andrea about where you want to start (in R) and one other course
      - Review lab web site, and make at least one annotation or comment

### 8 September 2020 (Zoom)

- Attending: Rick, Andrea, Anjali, Emily, Kayla, Anna, Shahir, Maureen, Yiming, Chelsea, Rachel, Sara
  - Excused: Michelle
- Agenda
  - Status of Joining Useful Tools
    - Discord - 1 missing
    - Asana - everyone joined
    - Hypothes.is - 7 missing from group space
  - [Webpage Biography](http://gilmore-lab.github.io/who-we-are.html)  
    - Include at least one link 
      - [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
  - Rick gave practice presentation [here](https://gilmore-lab.github.io/2020-09-09-flux)    
- To Do
  - Write Biography and send to the [Lab Email](mailto:psubrainlab@gmail.com) - Due Date 9/15/2020
  - Training requirements (CITI, Clery Act, Reporting Child Abuse) will be sent via Asana - Due Date 9/22/2020 

### 1 September 2020 (Zoom)

- Attending: Rick, Andrea, Yiming, Kayla, Maureen, Anjali, Shahir, Anna, Sara, Rachel, Emily
  - Excused: Michelle, Chelsea  
- Agenda
  - Introductions
  - Orientation to lab projects/themes
    - [Databrary](https://databrary.org)
    - [Datavyu](https://datavyu.org)
    - Open science
    - [Play & Learning Across a Year (PLAY)](https://play-project.org)
    - Development of motion perception
  - Some tools we use
    - R, RStudio
    - [Github](https://github.com/gilmore-lab)
    - Python, [PsychoPy](https://www.psychopy.org/)
    - Paperpile
    - [Hypothes.is](https://web.hypothes.is/)
  - Communication Tools
    - [Asana](https://asana.com/)
    - [Discord](https://discord.com/)



## Spring 2020

### April 6, 2020

- Attending: Rick, Andrea, Yiming, Michelle, Chelsea

- Agenda:  
  - What is everybody up to?

### March 30, 2020

- Attending: Rick, Andrea, Yiming, Michelle, Emily, Luka

- Agenda:

  - What is working well and what is not:
    - Needs to be more organized...some classes putting tons of work on line others, nothing
    - Hard to remember when things are due when professors don't put it on Canvas. Sylabus has changed, but Canvas wasn't updated.
    - Transition worked pretty well, communication and logistics could be better
    - Some classes don't meet by zoom at all or maybe once a week, but watching lots of videos of power point slides with professor narrating over it.
  - R code  
    - Census data

### March 9, 2020

Spring Break - No Meeting

### March 2, 2020

- Attending: Rick, Andrea, Yiming, Michelle, Emily, Amar, Luka, Sandy

- Agenda:  
  - Poster Groups: Finalize groups and topics for presentation
    - Michelle - Play pilot metadata - poster on Overleaf.com
    - Emily - Pire Project
    - Amar, Sandy, Luka - BehAV
      - Compare OpenPose, OpenFace, and human observer using Datavyu
        - Front, side, oblique, down, up Views
          - rules for each situation
          - full head in view = mom head (information to read a facial expression) and baby head, two separate coding columns
  - [DataCamp](https://learn.datacamp.com/)
  - Review Sex Differences QA

To Do:
  - Ouakinin, S. (2016). Teaching Psychology in Medicine: The Context, Methodologies and Doctor’s Professional Identity. Acta medica portuguesa, 29(12), 867–874. Retrieved from http://dx.doi.org/10.20344/amp.8384 - move to week after Psi Chi is due
  - Record Experimenter Name in Expermineter Note question of Qualtrics Survey - ARS add to protocol
  - Update stereo acuity to include instructions for when participant has difficulty - Yiming
  - Investigate motion staircase 383 and 20191204095223578: handedness, %correct
  - Add Line on both walls to line chair up 
  - PSU X-ling 4/3/2020 9am 127 Moore - Emily presenting talk - open to everyone - poster session 1-3pm hub
  
### February 24, 2020
- Attending: Rick, Andrea, Emily, Yiming, Amar
  - Sick: Rachel, Sandy (Work), Luka
  - Absent: Chelsea, Michelle

- Agenda:
  - Sex Differences 
    - Review Test Session Protocol ([html](https://gilmore-lab.github.io/sex-differences-in-motion-perception/protocol/test-session-protocol.html)) ([Rmd](https://gilmore-lab.github.i o/sex-differences-in-motion-perception/protocol/test-session-protocol.Rmd))
    - Look at participant plots for Temporal Threshold and Contrast Sensitivity results
  - Discuss [BehAV project coding](https://gilmore-lab.github.io/BehAV/facial-recognition.html)
- To Do: 
  - ARS: Change protocol to copy data every day - Andrea or Yiming will do this - note on discord when it is complete at the end of the day. **DONE 2020-02-26**
  - Procedure needed for checking what happened eg. 2 files same participant number
  - ARS: Check with Rachel participant 389 - why aren't there 2 files


### February 17, 2020
- Attending: Rick, Andrea, Yiming, Emily, Chelsea, Rachel, Amar
  - Excused - Michelle
  - Absent - Sandy, Luka

- Agenda:   
  - Presentation: [Posterdown Preview](https://github.com/gilmore-lab/student-testbed) - Emily
  - Discuss Sex Differences [Session QA](https://gilmore-lab.github.io/sex-differences-in-motion-perception/analysis/session_qa.html)
  - Discuss [BehAV project](https://github.com/gilmore-lab/BehAV) and data on [Box](https://psu.box.com/s/ytyd3hnz4614frjhq55oail9mge1l150)

- To Do:
  - Come up with ideas for Poster presenation.
  
### February 10, 2020

NO MEETING :)
  
### February 3, 2020

- Attending: Rick, Andrea, Yiming, Michelle, Rachel
  - Excused: Luka, Sandy, Amar
  - Missing: Emily, Chelsea

- Agenda:  
  - Type I (false positive), Type II (false negative) and statistical power
      - [Slides](talk-slides/type-I-type-II-errors.html)
  - Update on Sex Differences Project
      - Data collection status
      - Harmonizing data
   
### January 27, 2020

- Attending: Rick, Andrea, Michelle, Emily, Chelsea, Sandy, Luka, Rachel
    - Missing: Yiming, Amar

- Agenda:  
    - Introductions  
    - Submit 1-2 projects to the [Psi Chi](http://sites.psu.edu/psichi/) conference
        - [Application](http://sites.psu.edu/psichi/research-conference-2/) due March 16 by 5:00pm  
        - Conference on April 9, 2-4:30 pm, The Moore Building Atrium
    - Overview of projects  
        - [Sex Differences in Motion Perception](https://github.com/gilmore-lab/sex-differences-in-motion-perception)
            - Train everyone to collect data solo.
            - Changes to protocol
    - Plan for semester
       
- Next Meeting:
    - Schedule presentation for Sandy/Amar
    - Emily present posterdown 2/10/2020
    - Read paper

---

## Fall 2019

### December 12, 2019

- 8:00am Breakfast at the Waffle Shop

### December 5, 2019

Meeting Cancelled
  
### November 28, 2019 - No Lab

Happy Thanksgiving

### November 21, 2019
- Attending
    - Rick, Andrea, Yiming, Rachel, Emily, Michelle
    - Excused: Amar, Joseph
- Agenda
    - Review post processing procedures and QA
        - Possible Qualtrics Survey Changes (in new year)
            - add 'researcher notes' to end of Qualtrics survey to note any issues with filenaming, experimenter error, restarting the task, etc...
            - start the file name with 9 instead of 2019, keep month, day, hour, minutes, seconds 
            - do not keep the 2 digit random variable that Qualtrics makes 
            - change 2 digit random variable to m or c based upon the task run
    

### November 20, 2019 12 - 1:30
- Lab Ice Skating at Pegula Arena $5 to skate and $5 to rent skates

### November 14, 2019

- Attending
    - Rick, Andrea, Yiming, Rachel, Michelle, Amar, Luka
    - Excused: Emily
- Review of first day of Data collection
    - Good
        - Started data collection. Yay. We have begun
        - found small errors in protocol (e.g. need chair w/o wheels, protocol document)
        - randomization scheme for visual display works
    - Improve
        - Debriefing for after study complete - add to protocol
    - Other Notes
        - Keep track of gender and stop requestin in sona once we reacy 150 participants of each gender
        - look into BoxR Api to pull box data to TLT server
        - qualtrics post processing needs as QA
        - worked on QA for abramov replication during meeting

### November 7, 2019
- Attending
    - Rick, Andrea, Yiming, Emily, Rachel, Amar, Michelle
    - Excused: Luka
- Agenda
    - Emily and Rachel presenting paper: Chien, Y.-L., Hsieh, M. H., & Gau, S. S.-F. (2019). P50-N100-P200 sensory gating deficits in adolescents and young adults with autism spectrum disorders. Progress in neuro-psychopharmacology & biological psychiatry, 95, 109683. Retrieved from https://dx.doi.org/10.1016/j.pnpbp.2019.109683
        - Presentation [here](https://gilmore-lab.github.io/student-testbed/sensorygating.html)

### October 31, 2019
- Attending
    - Rick, Andrea, Yiming, Emily, Rachel, Luka, Amar, Joseph
- Agenda
    - Update [Sex Differences Data Collection Protocol](https://gilmore-lab.github.io/sex-differences-in-motion-perception/protocol/master-protocol.html) as a group
- To Do
    - Read paper for next week
        - Chien, Y.-L., Hsieh, M. H., & Gau, S. S.-F. (2019). P50-N100-P200 sensory gating deficits in adolescents and young adults with autism spectrum disorders. Progress in neuro-psychopharmacology & biological psychiatry, 95, 109683. Retrieved from https://dx.doi.org/10.1016/j.pnpbp.2019.109683
    - Students, please review [Sex Differences Data Collection Protocol](https://gilmore-lab.github.io/sex-differences-in-motion-perception/protocol/master-protocol.html) and write message in Discord Channel **study-sex-differences**.
  

### October 24, 2019
- Attending
    - Rick, Andrea, Yiming, Emily, Rachel
    - Excused: Amar
- Agenda
    - Update [Sex Differences Data Collection Protocol](https://gilmore-lab.github.io/sex-differences-in-motion-perception/protocol/master-protocol.html) as a group

### October 17, 2019
- Attending
    - Rick, Andrea, Yiming, Rachel, Luka, Michelle, Amar
    - Excused: Emily
- Agenda
    - Discuss R
        - Sex Differences Study - Protocol and Termiology
        - factors - category of some type of measure with a label
- Future Meeting
    - 11/7/2019 - Emily and Rachel will present: Chien, Y.-L., Hsieh, M. H., & Gau, S. S.-F. (2019). P50-N100-P200 sensory gating deficits in adolescents and young adults with autism spectrum disorders. Progress in neuro-psychopharmacology & biological psychiatry, 95, 109683. Retrieved from https://dx.doi.org/10.1016/j.pnpbp.2019.109683
    - Amar and Sandy will present:
- To Do
    - ARS send literature review protocol to Yiming

### October 10, 2019
- Attending
    - Rick, Andrea, Yiming, Emily, Joseph, Amar
    - Excused: Sandy
- Agenda
    - Yiming will give a practice master's presentation today


### October 3, 2019

- Attending
    - Rick, Yiming, Emily, Michelle, Amar, Andrea
    - Excused: Sandy, Luka, Rachel
- Agenda
    - Continue discussion of [Abramov et al. 2012](talk-slides/abramov-etal-2012.html)
    - Our study 
        - notate those with color deficiency instead of removing them from study
        - show mean and actual value graphs side by side
        


### September 26, 2019

- Attending
    - Rick, Andrea, Yiming, Luka, Amar, Rachel, Joseph
    - Excused: Emily, Michelle, Sandy
- Agenda
    - Discussion of [Abramov et al. 2012](talk-slides/abramov-etal-2012.html)
    - 'I' manipulate Independent variables, '*D*ey' manipulate Dependent variables
    - [How to Read an Academic Paper](talk-slides/how-to-read-academic-paper.html) Presentation
    

### September 19, 2019

- Attending
    - Rick, Andrea, Yiming, Luka, Rachel, Emily, Michelle, Amar
- Agenda
    - Status Update
    - Sex Differences 
        - lit review
        - create/update protocol for lit review (ars)
    - R bootcamp - [Slow R](https://psu-psychology.github.io/r-bootcamp-2019/talks/slow-r.html)
    - Instructions to log on to VPN for off campus
- To Do
    - Read paper for next week 9/26/2019
        - Abramov, I., Gordon, J., Feldman, O., & Chavarga, A. (2012). Sex & vision I: Spatio-temporal resolution. Biology of sex differences, 3(1), 20. bsd.biomedcentral.com. Retrieved from https://dx.doi.org/10.1186/2042-6410-3-20
    - Finish up assigned items on Asana
    - Start [Datacamp](https://www.datacamp.com) assignments
        - Log in > go to PSYCH 494 Research Studies > Assignments
        
### September 12, 2019

- Attending
    - Rick, Andrea, Yiming, Luka, Michelle, Emily, Rachel, Amar
- Agenda
    - [Vision: How it works, how it develops, and why you should care](https://gilmore-lab.github.io/csd-vision-2019-09-05/)

- To Do:
    - Online Training: CITI, Clery, Reporting Child Abuse
    - Biography in r markdown format saved as a .txt file including professional interests and 1 personal interest in addition to a picture if you like.
    - Use Discord to contact us

### September 5, 2019, 467 Moore

- Attending
    - Rick, Andrea, Yiming, Emily, Rachel, Michelle, Luka, Amar,
- Agenda
    - Introductions
    - Summary of active projects
        - Optic Flow
        - [Databrary](https://nyu.databrary.org/)
        - Open Science
        - behAV
        - [PLAY](play-project.org)
    - Goals
        - Learn R, Python, Datavyu
- To Do:
    - Online Training: CITI, Clery, Reporting Child Abuse
    - Biography in r markdown format saved as a .txt file including professional interests and 1 personal interest in addition to a picture if you like.


## Spring 2019  

### 2019-04-16

- Attending: Yiming, Andrea, Sarah, Michelle, Rick, Ashton
- Agenda:
    - Lab Name ([Google doc with terms](https://docs.google.com/document/d/1s3UZ7g3vR8vZja5EIu1sFraG5oOKZUQDG54wjqUMNDE/edit?usp=sharing))
    - How did the Psi Chi ($\Psi\chi$) presentations go?
    - Poster Presentation - Michelle
- Next Meeting: 4/30/2019 at Waffle Shop!
- Upcoming Events: 
    - 4/17/2019 - Lab Ice Skating, Pegula Ice Arena Community Rink, 12-1:30, $5 to skate, $5 rental
    - 4/30/2019 - Lab Breakfast Meeing 8:00am Waffle Shop

### 2019-04-09

- Attending: Rick, Andrea, Yiming, Ashton, Michelle, Zhichun
- Agenda:
    - Psi Chi project presentations
        - [Dluzneski, Rayes, Zhao, Gilmore, & Seisler, 2019](https://github.com/gilmore-lab/psi-chi-2019/blob/master/object-play_files/Psi_Chi_ASZ_2019.pdf)
        - [Shahriar, Gilmore, & Seisler, 2019](https://github.com/gilmore-lab/psi-chi-2019/blob/master/crawling-mode_files/Psi_Chi_Sarah_2019.pdf)
- Next Week:
    - Michelle Presenting
- Upcoming Events:
    - 4/11/2019 - Penn State Psi Chi Research Conference, 2-4:30 pm, in the Moore Building Lobby
    - 4/17/2019 - Lab Ice Skating, Pegula Ice Arena Community Rink, 12-1:30, $5 to skate, $5 rental
    - End of Semester Lab Breakfast Tuesday 4/30

### 2019-04-02

- Attending: Andrea, Yiming, Ashton, Michelle, Sarah
- Agenda:
    - Psi Chi project status review
    - Yiming continue to talk about ASD biological motion paper.

### 2019-03-26 

- Attending: Rick, Andrea, Yiming, Zhichun, Ashton, Michelle
- Agenda:
    - Yiming present paper about biological motion and ASD:
    Freitag, C. M., Konrad, C., Häberlen, M., Kleser, C., von Gontard, A., Reith, W., Troje, N. F., et al. (2008). Perception of biological motion in autism spectrum disorders. Neuropsychologia, 46(5), 1480–1494. Elsevier. Retrieved from https://dx.doi.org/10.1016/j.neuropsychologia.2007.12.025
- Notes: 
    - PsiChi Conference is April 11. 
    - Any accepted posters must be sent for printing by April 8.
- To Do:
    - Read the paper that was presented today for next week


### 2019-03-19

- Attending: Rick, Andrea, Yiming, Sarah, Sandy, Michelle
- Agenda:
    - Review Psi Chi abstracts
        - Object Play
            - look at hand grasp (R,L,both)/let go, stack/unstack
            - focus on fine movements related to grasping and manipulating, particularly interested in unimanual vs. bimanual, what kinds of actions (manual exploration, looking inside, stacking, drinking)
        - Gait Style
            - crawling bout = start until change of posture or stop then start again?
            - code hand at onset
            - static image of contralteral crawling
            - table of how much time was spent crawling
            - timeseries graph
        - Play Pilot Questionnaire
            - amount of time of sleep vs time from crawling to walking and color coded by type of childcare
    - To Do:
        - Complete [Empirical Research Application](https://sites.psu.edu/psichi/research-conference-2/) for submission. 
        - Email a copy to Andrea and Yiming for review on or before Wednesday morning at 8am.
        - file name: psychi_NAME_2019-03-21-v01
        - submissions due Friday March 22, 2019 before 6:00 pm

### 2019-03-12 

- Attending: Rick, Andrea, Yiming, Sarah, Ashton, Sandy, Michelle, Zhichun
- Agenda:
    - Review how to pull PLAY metadata (or any metadata) directly from the Databrary Spreadsheet and visualize using RStudio
    - Discuss [Psi Chi projects](https://github.com/gilmore-lab/psi-chi-2019)  
        - Sarah 
            - project: locomotion crawling/walking type 12 month olds (3 participants) (hand/knees crawling - contralateral vs. unilateral, start with left or right) 
            - create protocol document [Crawling Mode](https://github.com/gilmore-lab/psi-chi-2019/blob/master/crawling-mode.Rmd)
        - Ashton/Sandy/Zhichun  
            - project: view videos of stacking cups, solitary play
                - goal oriented motor movement = stacking/unstacking duration
            - create protocol document [Object Play](https://github.com/gilmore-lab/psi-chi-2019/blob/master/object-play.Rmd)
        - Michelle  
            - project: correlation walking/crawling vs. sleep from parent report and metadata
            - create protocol document

- Next Meeting: 
    - Bring Draft Abstracts (https://sites.psu.edu/psichi/research-conference-2/)  
        - Questions on the application include:
            5.	What is the title of your submission?

            6.	Briefly, what is the problem or major purpose of your research?
            
            7.	What procedures did you use?
            
            8.	What results did you expect? What did you find?
            
            9.	Briefly, what tables/figures do you plan to show?
            
            10.	Please list what references you already have (this can be a working list).
            
            11.	Please include a brief and thoughtful paragraph or two describing the importance of your research and its contribution to the field of psychology. Any personal interest in the topic may be included here.

    - new due date March 22, 2019

### 2019-02-26

- Attending: Rick, Andrea, Yiming, Zhichun, Sarah, Ashton
- Agenda:
    - Discuss Psi Chi projects
        - Sarah: 
            - Project: Play 1 hr videos, observing crawling types and see if it is related to handedness
                - Can we use Biopoints for videos?
            - Next Steps:
                - Have a coding scheme, do they need to be used in one coding column or separate columns or a combination.
        - Ashton, Sandy, Zhichun: Fine Motor Development 
            - Videos: Stacking Cups 
                - Staking vs. Unstacking
                - Transcripts (look at word bank for babies)
            - Next Steps    
        - Michelle: Questionnaire Data 
            - Statistics based upon age groups (12, 18, 24 months)
            - Next Steps:
                - Find actual questionnaire. (ARS to do)
                - determine which statistics to look at.

### 2019-02-19

- Attending: Rick, Andrea, Sarah, Yiming, Ashton, Zhichun  
- Agenda:  
    - Moco Psychophysics presentation by Yiming  
    
- To do: Submit a brief summary of Psi Chi project idea to Dr. Gilmore before 2/22.

### 2019-02-05

- Attending: Rick, Sarah, Yiming, Ashton, Zhichun, Michelle
- Agenda:
    - Motion psychophysics project (Yiming & Rick) postpone?
    - Psi Chi projects
        - PLAY pilot data (resources)
            - Adolph, K., Tamis-LeMonda, C. & Gilmore, R.O. (2017). PLAY Project: Pilot Data Collections. Databrary. Retrieved February 5, 2019 from <https://nyu.databrary.org/volume/444>.
            - Adolph, K., Tamis-LeMonda, C., Gilmore, R.O. & Soska, K. (2016). PLAY Project: NICHD Workshop (2016-12-16). Databrary. Retrieved February 5, 2019 from https://doi.org/10.17910/B7.254.
            - PLAY wiki: <https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php>
            - Sample report using `databraryapi`: <https://gilmore-lab.github.io/2018-10-15-nyu/PLAY-LEGO-report.html>
            - WordBank at Stanford: <https://wordbank.stanford.edu>
            
#### Using `databraryapi` with PLAY pilot data
            
To install `databraryapi` from its [GitHub repository](https://github.com/PLAY-behaviorome/databraryapi) into your RStudio project:

```
devtools::install_github("PLAY-behaviorome/databraryapi")
```
            
```
# load databraryapi
library(databraryapi)
```

### 2019-01-29

- Attending: Rick, Andrea, Yiming, Sandy, Michelle, Sarah
- Agenda:
    - Psi Chi projects
        - Datavyu coding (Michelle?)
        - Motion mega-analysis (Zhichun?)
    - Next week:
        - Yiming & Rick present on motion psychophysics
    - Discuss:
        - Hadad, B., Maurer, D., & Lewis, T. L. (2011). Long trajectory for the development of sensitivity to global and biological motion. *Developmental Science*, *14*(6), 1330–1339. Wiley Online Library. Retrieved April 17, 2012, from https://onlinelibrary.wiley.com/doi/10.1111/j.1467-7687.2011.01078.x/abstract
        - Biological motion demo: <https://www.biomotionlab.ca/bml-scrambled/>
        - [Mind Map](https://app.mindmup.com/map/_free/2019/01/dffb0ba023e711e9b80465b42db9671f) of Hadad et al. 2011

### 2019-01-15 

- Attending: Rick, Andrea, Ashton, Sarah, Yiming, Zichun, Michelle  
    - Sandy (sick)  
- Agenda:  
    - Introductions  
    - Submit 1-2 projects to the [Psi Chi](https://sites.psu.edu/psichi/) conference
        - [Application](https://sites.psu.edu/psichi/research-conference-2/) due March 23 by 4:00pm  
        - Conference on April 11, 2-4:30 pm 
    - Overview of projects  
        - [Development of Motion Sensitivity Meta-analysis](https://github.com/gilmore-lab/motion-metaanalysis)  
        - [Behaviors in developmental psychology research](https://github.com/dev-psych-behavior) project
        - [Databrary](https://databrary.org)  
            - apply computer vision to stored videos  
            - [Open Pose Example](https://www.youtube.com/watch?v=pW6nZXeWlGM)
        - [Datavyu](https://datavyu.org)
        - [Play & Learning Across a Year (PLAY)](https://nyu.databrary.org/volume/724)
            - teach coding this semester  
        - Wilkinson
        - Optic flow
            - [Paper in Progress](https://github.com/gilmore-lab/moco-psychophysics-child-adult)
        - PEEP [I](https://nyu.databrary.org/volume/248), [II](https://nyu.databrary.org/volume/339)  
        - R package for Databrary API-translate to python  
            - document  
            - sample uses  
        - [Annotating Databrary](https://github.com/gilmore-lab/annotating-databrary) project
    - Causes of Motion on Retina - diagram  
        - use this type of diagram to unpack methods/results in a research paper  
    - Plan for semester
        - Future Meeting - Discuss Adolph/Gilmore paper using Open Pose 
- Next Meeting:
    - Read: Hadad, B., Maurer, D., & Lewis, T. L. (2011). Long trajectory for the development of sensitivity to global and biological motion. *Developmental Science*, *14*(6), 1330–1339. Wiley Online Library. Retrieved April 17, 2012, from https://onlinelibrary.wiley.com/doi/10.1111/j.1467-7687.2011.01078.x/abstract
## Fall 2018  

## Goals

- Write-ups
    - child/adult MOCO psychophysics
    - infant MOCO EEG
    - child MOFO
- Preparation for PLAY
    - Train on locomotion coding on PLAY pilots
- Data science
    - Learn more about jupyter notebooks and python
- Read more primary source papers
- Launch new projects
    - [Annotating Databrary](https://github.com/gilmore-lab/annotating-databrary) project
    - [Development of Motion Sensitivity Meta-analysis](https://github.com/gilmore-lab/motion-metaanalysis)
    - [Behaviors in developmental psychology research](https://github.com/dev-psych-behavior) project

## Possible readings

- Finkelstein, A., Las, L., & Ulanovsky, N. (2016). 3-D Maps and Compasses in the Brain. *Annual Review of Neuroscience*, *39*, 171–196. Retrieved from https://dx.doi.org/10.1146/annurev-neuro-070815-013831
- Egnor, S. E. R., & Branson, K. (2016). Computational Analysis of Behavior. *Annual Review of Neuroscience*, *39*, 217–236. Retrieved from https://dx.doi.org/10.1146/annurev-neuro-070815-013845
- Kaplan, R., Schuck, N. W., & Doeller, C. F. (2017). The Role of Mental Maps in Decision-Making. *Trends in Neurosciences*, *40*(5), 256–259. Retrieved from https://dx.doi.org/10.1016/j.tins.2017.03.002
- Rowland, D. C., Roudi, Y., Moser, M.-B., & Moser, E. I. (2016). Ten Years of Grid Cells. *Annual Review of Neuroscience*, *39*, 19–40. Retrieved from https://dx.doi.org/10.1146/annurev-neuro-070815-013824

## Schedule

### 2018-12-07  

9:00am - Breakfast at the Waffle Shop Downtown

### 2018-11-30  

- Attending: Andrea, Yiming, Sandy, Rick, Michelle, Ashton  
- Agenda:  
    - Discuss: Land, M., Mennie, N., & Rusted, J. (1999). The roles of vision and eye movements in the control of activities of daily living. Perception, 28(11), 1311–1328. Retrieved from https://dx.doi.org/10.1068/p2935 (Ashton & Sandy lead). [Github](student-testbed/LandM_etal_1999_paper_presentation.md)  
- Next Meeting:  
    - Breakfast at the Waffle Shop Downtown, 9am 

### 2018-11-23  

THANKSGIVING BREAK - No Meeting  

### 2018-11-16   

SNOW DAY! - No Meeting  

### 2018-11-09  

- Attending: Andrea, Yiming, Rick, Michelle, Zhichun  
- Agenda:
    - Work on [Development of Motion Sensitivity Meta-analysis](https://github.com/gilmore-lab/motion-metaanalysis) specifically grating-motion  
    - Work on [Annotating Databrary](https://github.com/gilmore-lab/annotating-databrary) project
    
- Next Meeting:  
    - Read: Land, M., Mennie, N., & Rusted, J. (1999). The roles of vision and eye movements in the control of activities of daily living. Perception, 28(11), 1311–1328. Retrieved from https://dx.doi.org/10.1068/p2935 (Ashton & Sandy lead). [Github](student-testbed/LandM_etal_1999_paper_presentation.md)
    
### 2018-11-02

- Attending: Andrea, Yiming, Sandy, Rick, Michelle, Ashton, Zhichun
- Agenda:
    - Choose readings for next few weeks
    - Work on [Development of Motion Sensitivity Meta-analysis](https://github.com/gilmore-lab/motion-metaanalysis)    
    - ~~Work on [Annotating Databrary](https://github.com/gilmore-lab/annotating-databrary) project~~
    - ~~(if time) Work on [Behaviors in developmental psychology research](https://github.com/dev-psych-behavior) project~~
- Next week:
    - Read: Land, M., Mennie, N., & Rusted, J. (1999). The roles of vision and eye movements in the control of activities of daily living. Perception, 28(11), 1311–1328. Retrieved from https://dx.doi.org/10.1068/p2935 (Ashton & Sandy lead).
        - What did they do? What did they find? Why does it matter? (ideally in R Markdown document).
    - Project status reports 

### 2018-10-26  

- Attending: Rick, Andrea, Yiming  
- Agenda: Start two new projects    
    - [Annotating Databrary](https://github.com/gilmore-lab/annotating-databrary)
    - [Development of Motion Sensitivity Meta-analysis](https://github.com/gilmore-lab/motion-metaanalysis)
- Next week:    

### 2018-10-19

- Attending: Rick, Andrea, Yiming, Michelle, Sarah, Ashton  
- Agenda:  
    - Yiming present the MOCO project  
    - Next project meta analysis neural and behavioral literature  
- Next week:  
    - Meta analysis of motion  
    - Developmental research methods  

### 2018-10-12

NO MEETING TODAY

### 2018-10-05

NO MEETING TODAY

### 2018-09-28  

- Attending: Rick, Ashton, Sandy, Zhichun, Michelle  
- Agenda:  
    - Lab Activities: (mainly R) - Who has done it, how’s it going, do we like it  
    - Dr. Gilmore won’t be here next week - going to a conference  
	    - discussed [Devsec](https://www.srcd.org/meetings/special-topic-meetings/devsec18) (the conference he’s going to)   
  	- Secondary data - our knowledge of it; pros and cons
    - Poster that was made for databrary and datavyu (PLAY Project)  
    - Databrary play coding (this is what he will be discussing during the conference)  
- Next Meeting:  
    - No meeting on 10/5 - Dr. Gilmore will be at the conference  


### 2018-09-21  

- Attending: Rick, Andrea, Yiming, Michelle, Sandy, Ashton
- Agenda: Discuss R  
    - [Slow R talk](https://psu-psychology.github.io/r-bootcamp-2018/talks/slow-r.html) 
    - R Studio Server: https://lat.tlt.psu.edu/home/remoteaccess/oss-web-apps/ 
- Next Meeting: 
    - Try the steps in the Slow R Talk on the R Studio server
    - Datacamp class: PSYCH 494 Fall 2018 
    - A link to reading will be sent out soon 

### 2018-09-14  

- Attending: Rick, Andrea, Yiming, Sarah, Zhichun, Michelle, Sandy
- Agenda:  
    - Training and Schedule Update 
    - Discuss Toddlers are “tiny apes” who share 96 per cent of same gestures, scientists find. (2018, September 11). The Daily Telegraph. Retrieved September 12, 2018, from https://www.telegraph.co.uk/science/2018/09/11/toddlers-tiny-apeswho-share-96pcof-gestures-scientists-find/ Original Article: https://doi.org/10.1007/s10071-018-1213-z 
- Next Meeting:  Work on R

### 2018-09-07 Friday (**350 Moore!**)

- Attending: Rick, Andrea, Yiming, Michelle, Ashton, Sandy, Sarah  
- Agenda:  
    - Check-in/update 
    - Discuss Murray, S. O., Schallmo, M.-P., Kolodny, T., Millin, R., Kale, A., Thomas, P., Rammsayer, T. H., et al. (2018). Sex Differences in Visual Motion Processing. *Current Biology: CB*. Retrieved from https://dx.doi.org/10.1016/j.cub.2018.06.014. | [Discussion notes](lab-mtgs/notes-murray-2018.html) | 
- Next Meeting:  
  - Read: Toddlers are “tiny apes” who share 96 per cent of same gestures, scientists find. (2018, September 11). The Daily Telegraph. Retrieved September 12, 2018, from https://www.telegraph.co.uk/science/2018/09/11/toddlers-tiny-apeswho-share-96pcof-gestures-scientists-find/
  
### 2018-08-29 Wednesday

- Attending: Rick, Andrea, Yiming, Michelle, Ashton 
- Agenda:
    - Introductions
    - Overview of projects
        - [Databrary](https://databrary.org)
        - [Datavyu](https://datavyu.org)
        - [Play & Learning Across a Year (PLAY)] (https://nyu.databrary.org/volume/724)
        - Wilkinson
        - Optic flow
        - PEEP [I](https://nyu.databrary.org/volume/248), [II](https://nyu.databrary.org/volume/339)
    - Plan for semester
- Next Meeting:
    - **Wednesday, 9/5, 9a, 444 Moore**
    

## Spring 2018  

## Goals

- Submit posters to Psi Chi conference on the "size matters" project, infant MOCO, PLAY.
- Submit papers from infant MOCO, child/adult MOCO psychophysics
- Analyze the child MOFO
- Train on locomotion coding on PLAY pilots
- Learn more about jupyter notebooks and python
- Read more primary source papers
- Turn data from "size matters" into a Shiny app
- Write/edit LaTex posters in RMarkdown
- Discuss new federal regulations, Common Rule

## Let's read

- Finkelstein, A., Las, L., & Ulanovsky, N. (2016). 3-D Maps and Compasses in the Brain. *Annual Review of Neuroscience*, *39*, 171–196. Retrieved from https://dx.doi.org/10.1146/annurev-neuro-070815-013831
- Egnor, S. E. R., & Branson, K. (2016). Computational Analysis of Behavior. *Annual Review of Neuroscience*, *39*, 217–236. Retrieved from https://dx.doi.org/10.1146/annurev-neuro-070815-013845
- Kaplan, R., Schuck, N. W., & Doeller, C. F. (2017). The Role of Mental Maps in Decision-Making. *Trends in Neurosciences*, *40*(5), 256–259. Retrieved from https://dx.doi.org/10.1016/j.tins.2017.03.002
- Rowland, D. C., Roudi, Y., Moser, M.-B., & Moser, E. I. (2016). Ten Years of Grid Cells. *Annual Review of Neuroscience*, *39*, 19–40. Retrieved from https://dx.doi.org/10.1146/annurev-neuro-070815-013824

## Schedule

### 2018-05-03 Breakfast

- Lab breakfast 8:30am at E. College Waffle Shop

### 2018-04-26 **No Meeting**

### 2018-04-19 Thursday

- Attending:
- Agenda
    - Create reproducible workflow for using [ShareLaTeX](https://www.sharelatex.com/) 
        - Learn how to [sync GitHub and ShareLaTeX](https://www.sharelatex.com/blog/2015/02/10/shareLaTeX-github-sync.html)

### 2018-04-12 Thursday

- Attending: Rick, Andrea, Sarah, Charmi, Alyssa
- Agenda
    - Practice Poster Presentations
        - Infant brain responses differentiate between optic flow patterns and motion speeds - Alyssa 
        - Reanalyzing Shared Data about Brains and Behavior - Charmi 
    - Review Databrary API - Package to interact with Databrary using R
        - devtools::load_all()  - use to load tool
          - summarize_demog(volume = VOLNUMBER)
          - download videos
          - BUG: list_assets_by_type (type = "text") 
          - list_people: only show authorized people
          - instructions: github PLAY-behaviorome
          - can 2 different accounts be logged in at the same time?
        
### 2018-03-22 Thursday

- Attending: Rick, Andrea, Sarah, Charmi, Alyssa
- Agenda  
    - Posters for upcoming undergraduate conferences
        - Charmi and Alyssa will submit Friday
    - Diagnose issue with PLAY pilot crawling and walking onsets (ROG)
        - Review videos for issues with locomotion.csv to confirm survey answers
    - Give Rick feedback about [IBAD paper](https://github.com/PLAY-behaviorome/ibad-lets-PLAY) plots.
    - Discuss: Ballard, D. H., Hayhoe, M. M., & Pelz, J. B. (1995). Memory representations in natural tasks. Journal of cognitive neuroscience, 7(1), 66–80. Retrieved from https://dx.doi.org/10.1162/jocn.1995.7.1.66  

### 2018-03-15 Thursday  

- Attending: Rick, Andrea, Sarah, Charmi, Amber, Alyssa
- Agenda  
    - Discuss:
        - Databrary User Growth Plot  
            - How to create plot using R  
            - Aesthetic feedback provided  
        - [Galaxy S9](https://www.youtube.com/watch?v=5_-NKRVn7IQ) - New Camera Phone with Iris
        - Fortenbaugh, F. C., Hicks, J. C., Hao, L., & Turano, K. A. (2006). High-speed navigators: Using more than what meets the eye. Journal of vision, 6(5), 565–579. Retrieved from https://dx.doi.org/10.1167/6.5.3  
        - [databrary-r-api overview](https://rawgit.com/gilmore-lab/databrary-r-api/master/vignettes.html) - Shared data in one or more repositories that can be easily accessed, visualized, and analyzed because the data are in a common format. A new way interact with data on Databrary 
        - [R commands to access Databrary](https://github.com/gilmore-lab/databrary-r-api)
- Next Meeting:  
    - Read: Ballard, D. H., Hayhoe, M. M., & Pelz, J. B. (1995). Memory representations in natural tasks. Journal of cognitive neuroscience, 7(1), 66–80. Retrieved from https://dx.doi.org/10.1162/jocn.1995.7.1.66


### 2018-03-01 Thursday

- Attending: Rick, Andrea, Sarah, Charmi, Alyssa
- Agenda  
    - Discuss: 
        - Talk about RIDIR NSF submission - for research infrastructure
        - Project Updates  
            - Infant MOCO  
                - outline paper  
                - switch from R server to RStudio local  
            - Map of PLAY project locations  
                - ggmap using census data  
                - Create Shiny App - In progress 
            - PLAY pilot data survey results and workflow analysis to aid in future data collection   
        - [Chapter 2](pdfs/gibson-1979-ch-2.pdf) - Gibson, J. J. (2014). The Ecological Approach to Visual Perception: Classic Edition. Psychology Press.  
        - [Galaxy S9](https://www.youtube.com/watch?v=5_-NKRVn7IQ) - New Camera Phone with Iris
- Next Meeting: 3/15/2018
    - Pick K. Adolph paper and find related videos on Databrary - crawling vs. walking

### 2018-02-22 Thursday

- Attending: Rick, Andrea, Sarah, Charmi, Amber, Quendresa, Alyssa  
- Agenda 
    - Discuss 
        - Watch 'Torpedo Gannet Diving!' Video
        - Lee, D. N., & Reddish, P. E. (1981). Plummeting gannets: a paradigm of ecological optics. Nature, 293, 293. Nature Publishing Group. Retrieved from https://dx.doi.org/10.1038/293293a0
        - <https://youtu.be/1Cp1n_vPvYY>
- Next Meeting     
        - Time to contact issues in different sports
        - Difference between aiming and steering, balance, object manipulation
        - Vision testing tools - Teller Acuity Cards
- Next Meeting       
    - Read [Chapter 2](pdfs/gibson-1979-ch-2.pdf): Gibson, J. J. (2014). The Ecological Approach to Visual Perception: Classic Edition. Psychology Press. Retrieved from https://market.android.com/details?id=book-8BSLBQAAQBAJ  
    
### 2018-02-15 Thursday

- Attending: Rick, Andrea, Alyssa, Sarah, Amber, Charmi 
- Agenda 
    - Discuss 
        - Visual Acuity Paper: Nityananda, V., Tarawneh, G., Henriksen, S., Umeton, D., Simmons, A., & Read, J. C. A. (2018). A Novel Form of Stereo Vision in the Praying Mantis. Current biology: CB. Retrieved from https://dx.doi.org/10.1016/j.cub.2018.01.012 
        - Vestibular motion 
        - [Psi Chi Conference](https://sites.psu.edu/psichi/research-conference-2/) 
              - Application due March 23rd at 4:00 pm - [Pertinent Information](https://docs.google.com/document/d/1CBm5eAsiAbZv1Iol2dasNsdMb1KHkp4srFkl2pgE2vY/edit?usp=sharing)
              - Draft after spring break 
- Next Meeting 
    - read: Lee, D. N., & Reddish, P. E. (1981). Plummeting gannets: a paradigm of ecological optics. Nature, 293, 293. Nature Publishing Group. Retrieved from https://dx.doi.org/10.1038/293293a0
    - Discuss Teller Acuity Cards and Stereo Vision Tests


### 2018-02-08 Thursday

- Attending: Rick, Andrea, Charmi, Amber, Alyssa, Sarah
- Agenda
    - Discuss
        - Excerpt from Palmer chapter on [Fourier analysis](pdfs/20180202145140744.pdf).
        - Watch [video](https://youtu.be/spUNpyF58BY)
        - Rick's [lecture notes](https://psu-psychology.github.io/psy-525-vision-spring-2017/slides/2018-01-29-retinal-image.html#34) on Fourier analysis
        
- Next Meeting 
    - Read paper on Visual Acuity

### 2018-02-01 Thursday

- Attending:
- Agenda  
    - Reports
        - Lab Dinner graduate recruit - Monday 2/12 @ 5:45 pm @ The Field
    - Discuss
        - Jackson, A.F., & Bolger, D. J. (2014) The neurophysiological bases of EEG and EEG measurement: a review for the rest of us. *Psychophysiology*. 2014 Nov;51(11):1061-71. Retrieved from https://dx.doi.org/10.1111/psyp.12283. Epub 2014 Jul 17.

- Next Meeting

### 2018-01-25 Thursday

- Agenda
    - Reports
        - Psi Chi dates
            - Deadlines: Application due ***March 23rd at 4:00 pm***
            - Conceptual or Empirical research application: Submit as an email attachment (MS Word document) to psichi.honorsociety.psu@gmail.com by March 23, 2018 by 6 PM.
            - Need to figure out what questions were more important in the domain in order to extract data from.
            - Psi Chi Conference Date: **April 12th 2-4:30pm**
        - [Undergrad conference dates](https://undergradresearch.psu.edu/exhibition/)
             - Poster Presentation—traditional research poster
             - Performance—Limited to 5 minutes
             - Oral Presentation (1 slide/visual, 5 minutes)—students will present their research/creative work in 5 minutes using 1
             - PowerPoint slide or 1 visual display (i.e. an original piece of visual art)
             - Entries will be accepted ***February 12-March 28, 2018***
             - Poster Presentation Date: **April 18th, 5-8pm**
      - Discuss: Cohen, M. X. (2017). Where Does EEG Come From and What Does It Mean? *Trends in Neurosciences*, *40*(4), 208–218. Retrieved from https://dx.doi.org/10.1016/j.tins.2017.02.004. | [Notes](lab-mtgs/notes-cohen-2017.html) |
- Next Meeting
    - Jackson, A.F., & Bolger, D. J. (2014) The neurophysiological bases of EEG and EEG measurement: a review for the rest of us. *Psychophysiology*. 2014 Nov;51(11):1061-71. Retrieved from https://dx.doi.org/10.1111/psyp.12283. Epub 2014 Jul 17.
    - Talk about the grant that Dr. Gilmore is writing about testing different brain measuring equipment

### 2018-01-18 Thursday

- Agenda
    - Goal-setting
    - Assign Psi Chi submission info and report (Sarah)
    - Info about undergrad research conference (Charmi)
    - Discuss [jupyter notebooks](https://jupyter.org) and Rick's preliminary work on [`pliers`](https://github.com/tyarkoni/pliers), a tool to apply computer vision/machine learning tools to images, video, and audio.
- Next meeting
    - Cohen, M. X. (2017). Where Does EEG Come From and What Does It Mean? *Trends in Neurosciences*, 40(4), 208–218. Retrieved from https://dx.doi.org/10.1016/j.tins.2017.02.004
    

## Fall 2017

## 2017-11-30

- Attending
    - Rick, Andrea, Charmi, Sarah, Alyssa
- Agenda
    - Announcements
        - Lab breakfast next Thursday, 2017-12-7 at E. College Waffle Shop
    - Old business
        - Stand up reports
            - Andrea
            - Alyssa
                - Infant MOCO EEG poster for ICIS 2018. [Poster draft](https://github.com/gilmore-lab/infant-moco-eeg/blob/master/pubs/icis-2018-poster/icis-2018-abstract-2017-12-01.Rmd). [Analysis](https://github.com/gilmore-lab/infant-moco-eeg/tree/master/analysis).
            - Sarah
            - Minnie
                - Submitted optic flow paper to computer vision/agriculture journal.
            - Charmi
                - [Brain-Behavior data repo](https://github.com/gilmore-lab/brain-behavior-data).
        - Read and discuss: MacLean, Evan L., et al (2014). The evolution of self-control. *Proceedings of the National Academy of Sciences*, *111*(20), E2140-E2148. Retrieved from <https://dx.doi.org/10.1073/pnas.1323533111>. [Data on FigShare](https://figshare.com/articles/MacLean_et_al_PNAS_2014_Self-Control_Data/5579335).
## 2017-11-09

- Attending
    - Rick, Minnie, Andrea, Charmi, Alyssa
- Agenda
    - Announcements
        - **No lab meeting Thursday, 2017-11-16**
        - Next lab meeting Thursday, 2017-11-30.
    - Old business
        - Stand-up reports
        - Finish background discussion on optic flow projects. [Rick's developmental area talk](https://gilmore-lab.github.io/2017-10-18-the-whole-elephant).
    - New business
      - Read and discuss: MacLean, Evan L., et al (2014). The evolution of self-control. *Proceedings of the National Academy of Sciences*, *111*(20), E2140-E2148. Retrieved from <https://dx.doi.org/10.1073/pnas.1323533111>. [Data on FigShare](https://figshare.com/articles/MacLean_et_al_PNAS_2014_Self-Control_Data/5579335).

## 2017-11-02

- Attending
    - Rick, Charmi, Bin, Alyssa
- Agenda
    - Announcements
        - **No lab meeting Thursday, 2017-11-16**
    - Old business
        - [Size matters project](https://github.com/gilmore-lab/brain-behavior-data) (Charmi lead)
            - Rick, Charmi schedule meeting time
        - [Infant MOCO project](https://github.com/gilmore-lab/moco) (Alyssa lead)
        - [Child MOFO project](https://github.com/gilmore-lab/child-motion-form) (Michael lead)
        - Databrary (Andrea lead)
        - PLAY (Rick lead)
    - New business
        - Background on optic flow projects. [Rick's developmental area talk](https://gilmore-lab.github.io/2017-10-18-the-whole-elephant).
        
### 2017-10-26

- Attending
    - Rick, Charmi, Sara, Bin, Alyssa
- Agenda
    - Old business
        - [Size matters project](https://github.com/gilmore-lab/brain-behavior-data) (Charmi lead)
            - Rick, Charmi schedule meeting time
        - [Infant MOCO project](https://github.com/gilmore-lab/moco) (Alyssa lead)
        - [Child MOFO project](https://github.com/gilmore-lab/child-motion-form) (Michael lead)
    - New business
        - [Galaxy project](https://usegalaxy.org/)
        - PLAY project. | [Pilot data on Databrary](https://nyu.databrary.org/volume/254) | [Additional data](https://nyu.databrary.org/volume/444) | [GitHub repo](https://github.com/PLAY-behaviorome) |
            - Brainstorm about how to represent, visualize data
        - Developing expertise in [Xaringen](https://github.com/gilmore-lab/xaringen) package for making presentations.
        - Developing expertise in [dplyr](https://dplyr.tidyverse.org/).
            - Specific goal: extract participant demographics from infant MOCO & infant MOFO datasets.
        - Developing expertise in [papaja](https://github.com/crsh/papaja)
            - Specific goal: convert working manuscripts into this format
        - Develop workflow for 're-analyzing' data stored on OSF. [This](https://github.com/chartgerink/osfr) may be helpful.

### 2017-10-12

- Attending
- Agenda
    - Old business
        - [Size matters project](https://github.com/gilmore-lab/brain-behavior-data) (Charmi lead)
        - [Infant MOCO project](https://github.com/gilmore-lab/moco) (Alyssa lead)
    - New business
        - Discuss [Leonard, Lee, & Schultz 2017](lab-mtgs/leonard-lee-schultz-2017.html)

### 2017-10-05

- Agenda
    - Attending
        - Rick
    - Old business
        - [Size matters project](https://github.com/gilmore-lab/brain-behavior-data) (Charmi lead)
            - ROG add Charmi to GitHub repo
        - [Infant MOCO project](https://github.com/gilmore-lab/moco) (Alyssa lead)
            - ROG check on local pull/push; resolve conflict with Andrea's latest
    - New business
        - Read and discuss next week: Leonard, J. A., Lee, Y., & Schulz, L. E. (2017). Infants make more attempts to achieve a goal when they see adults persist. *Science*, *357*(6357), 1290–1294. Retrieved from <https://dx.doi.org/10.1126/science.aan2317>. [video sample](https://science.sciencemag.org/highwire/filestream/699641/field_highwire_adjunct_files/1/aan2317s1.mp4). [Data & code](https://osf.io/xjz8e/).

### 2017-09-28

- Agenda
    - Attending
        - Charmi, Sarah, Alyssa, Bin, Andrea, Rick
    - New business
        - [Size matters project](https://github.com/gilmore-lab/brain-behavior-data) (Charmi lead)
        - [Infant MOCO project](https://github.com/gilmore-lab/moco) (Alyssa lead)
        - [PLAY Project Pilot](https://nyu.databrary.org/volume/254#panel-data)

### 2017-09-14

- Agenda
    - Attending
        - Rick, Andrea, Alyssa, Charmi, Bin
    - Old business
        - ACI-ICS account creation
            - Lab rstudio projects are in `/storage/home/rog1/rstudio/`
            - Log in to `https://rstudio.aci.ics.psu.edu`
            - From RStudio, open "Tools/Shell..."
            - At command line, enter "pwd" and hit ENTER
            - Then enter "cd /storage/home/rog1/rstudio"
        - DataCamp
        - Databrary
    - New business
        - Assign staff to teams
            - Size matters project, see
                - Herculano-Houzel, S., Catania, K., Manger, P. R., & Kaas, J. H. (2015). Mammalian Brains Are Made of These: A Dataset of the Numbers and Densities of Neuronal and Nonneuronal Cells in the Brain of Glires, Primates, Scandentia, Eulipotyphlans, Afrotherians and Artiodactyls, and Their Relationship with Body Mass. Brain, behavior and evolution, 86(3-4), 145–163. Retrieved from https://dx.doi.org/10.1159/000437413.
                - <https://www.ted.com/talks/suzana_herculano_houzel_what_is_so_special_about_the_human_brain#t-788756>
                - Charmi (lead)
            - Infant motion coherence (MOCO) EEG project. | [Databrary](https://nyu.databrary.org/volume/146) |
                  - Alyssa (lead)
            - Child MOCO psychophysics | [Databrary](https://nyu.databrary.org/volume/218) |
            - Child MOFO EEG project | [Databrary](https://nyu.databrary.org/volume/144) |
                - Add SfN poster to Databrary
        - Lab how-tos
            - On-boarding: CITI, Child Abuse, Databrary, ACI-ICS 
            - Slack, Asana, DataCamp, PaperPile
    - Next week
        - Rick's talk about optic flow, probably 
based on [this](https://gilmore-lab.github.io/temple-2017-02-27)

### 2017-09-05

- Agenda
    - Apply for [ACI-ICS accounts](https://ics.psu.edu/advanced-cyberinfrastructure/accounts/). Rick (rog1) is principal investigator (PI).
    - [Register](https://databrary.org/register) for affiliate access to Databrary. Andrea will provide further details.
    - Plan work topics for semester
        - Learn R Markdown
        - R Markdown for lab/project management
            - Lab page(s)
            - Project sites or pages
        - Active projects
            - [Databrary](https://databrary.org) and [Datavyu](https://datavyu.org)
            - Infant MOCO EEG
            - Child motion form [child-motion-form](https://github.com/gilmore-lab/child-motion-form)
            - [Child motion psychophysics](https://github.com/gilmore-lab/child-motion-psychophysics)
            - [PLAY](https://nyu.databrary.org/volume/254) and [pilot data](https://nyu.databrary.org/volume/444) 
        - Read primary source literature papers
- Attending
    - Rick, Andrea, Andrew, Charmi, Alyssa, Bin LIAO

### 2017-08-31

- Agenda
    - Meeting time
        - Move to 8:15 am on Tuesdays, starting 9/5.
    - Goals for the semester
        - Read and understand primary literature
    - Announcements
        - Rick giving [ACI-ICS talk](https://gilmore-lab.github.io/aci-ics-2017-09-07/) on Thursday, September 7, 1:30-3:00 pm in 223A HUB.
        - Moved to 503 Moore
        - Fun illustration of [kestrel head stabilization](https://i.imgur.com/MbuGlD2.gifv).
- Attending
    - Rick, Andrea, Alyssa (2nd year in lab), Lena, Bin, Andrew


## Next Meeting: March 14, 2017

- Katie's report on Paperpile
- Read and discuss (Rick, Daved, Michael leads)
    + Warren, W. H. (2009). How do animals get about by vision? Visually controlled locomotion and orientation after 50 years. British Journal of Psychology, 100(S1), 277–281. <https://doi.org/10.1348/000712609X414150>
- No meeting 2017-03-21

## Spring 2017 Lab Meeting Minutes

- 2017-02-28
    - Reports on GitHub/Databrary dataset quality check for
      + Child Motion Form (MOFO)
      + Child/Adult MOCO Behavior
    - Read and discuss <https://aeon.co/essays/how-cognitive-maps-help-animals-navigate-the-world>
- 2017-02-21
    - Updates about PLAY project demographics
    - Discuss GitHub/Databrary dataset quality check for
        + Infant MOCO
        + Child Motion Form (MOFO)
        + Child/Adult MOCO Behavior
    - Discuss [WordBank](https://wordbank.stanford.edu)
- 2017-02-07
    - Katie's report on [Paperpile](https://paperpile.com)
        + Katie will demo its use on the RIDIR grant next week.
    - Plan for using <https://alias.libraries.psu.edu/ERESOURCES/PSU01568> to collect and visualize some data for the PLAY project
- 2017-01-31
    - Watch & discuss this video: <https://youtu.be/NGFO0kdbZmk>
    - Discuss preregistration
          + Read: Chambers, C., Munafò, M., & signatories, more than 80. (2013, June 5). Trust in science would be improved by study pre-registration. The Guardian. Retrieved from <https://www.theguardian.com/science/blog/2013/jun/05/trust-in-science-study-pre-registration>
          + Read: Frank, M. (2016, July 22). Preregister everything. <https://babieslearninglanguage.blogspot.com/2016/07/preregister-everything.html>.
- 2017-01-24
    + Check-in on DataCamp
    + Side-by-side evaluation of [Zotero](https://www.zotero.org) vs. [PaperPile](https://paperpile.com/)
    + Project-by-project workflow review
        + [Symmetry sorting](https://github.com/gilmore-lab/symmetry-sorting)
        + [Infant moco](https://github.com/gilmore-lab/moco)
        + [Child moco behavior](https://github.com/gilmore-lab/moco-3-pattern-psychophysics)
        + [Child motion form (MOFO)](https://github.com/gilmore-lab/child-motion-form) vs. [This](https://github.com/gilmore-lab/mofo)
    + Compare to <https://psu-psychology.github.io/psy-511-reproducible-research-spring-2017/in-class-activities/2017-01-23.html#22>
    + And to PLAY Project [wiki](https://dev1.ed-projects.nyu.edu/wikis/docuwiki/doku.php/collection)
- 2017-01-17
    - Read and discuss: Munafò, M. R., Nosek, B. A., Bishop, D. V. M., Button, K. S., Chambers, C. D., Sert, N. P. du, … Ioannidis, J. P. A. (2017). A manifesto for reproducible science. Nature Human Behaviour, 1, 0021. <https://doi.org/10.1038/s41562-016-0021>.
        - Slides. [HTML](talk-slides/munafo-etal-2017.html). [Rmd](talk-slides/munafo-etal-2017.Rmd)
    - Discuss plan for learning R and R Markdown using [DataCamp](https://www.datacamp.com) courses.
        + Sign-up link: <https://www.datacamp.com/groups/1b7b16b432bbc53dc4edfe34923406705194b3e7/invite>
- 2017-01-10
	+ Attending
	+ Agenda
		* Complete Forms for Credit
		* Ensure all training is complete
		* This semester we will focus on learning R Markdown
			- Training Videos
			- Mini projects
			- Ultimate goal: Convert current lab website to R Markdown 	
  + Remember to check the Slack channel: <https://gilmore-lab.slack.com>

## Fall 2016
- 2016-10-25
	+ Attending - Rick, Andrea, Amber, Alyssa, Sam, Michael O., Shivani, Michelle
	+ Agenda 
		* Discuss figures for moco behavioral child and adult data
		* Discuss Child Study Center talk
		
- 2016-10-11
	+ Attending - Rick, Andrea, Amber, Daved, Michael O., Katie, Hifzah, Alyssa, Michelle  
	+ Agenda
		* Discuss: Fesi, J.F., Thomas, A.L., & Gilmore, R.O. (2014). Cortical responses to optic flow and motion contrast across patterns and speeds. Vision Research, 100, 56–71. [doi:10.1016/j.visres.2014.04.004](https://doi.org/10.1016/j.visres.2014.04.004).
		* Review draft [poster for SfN 16](https://github.com/gilmore-lab/child-motion-form/blob/master/pubs/sfn-16-poster/poster_landscape.pdf). 
	+ Action Items  
		*  Write Biography in Markdown Format for [lab website](https://gilmore-lab.github.io/pages/students.html) - [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)  
			- Incorporate at least **one link** and send to lab gmail account  
			- Michael D., Daved, Alyssa  
			
- 2016-09-27
	+ Attending - Rick, Andrea, Amber, Alyssa, Michael O., Hifzah, Sam
	+ Agenda
		* Discuss 2nd Chapter 'An Introduction to Vision Science': [gilmore-lab/references/Palmer-1999/palmer-1999-chap-2.pdf](https://psu.app.box.com/files/0/f/11123835210/Palmer-1999)
	+ Action Items
		* Everyone Read Fesi 2011 'Distinct cortical responses to 2D figures defined by motion contrast' found      
			- On Box: [gilmore-lab/references/LabReading/Fesi2011.pdf](https://psu.app.box.com/files/0/f/11458072981/1/f_96049144629)  
			- On PubMed: [Distinct cortical responses to 2D figures defined by motion contrast](https://www-ncbi-nlm-nih-gov.ezaccess.libraries.psu.edu/pubmed/21820002)  
		*  Write Biography in Markdown Format - [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and send to lab gmail account
			- Michael D., Daved, Alyssa
		* Required Training: Complete by 9/15/2016  
		  Send all Certificates of Completion to the lab gmail account
			- [Clery Act Training](https://lrn.psu.edu/)  
				- Daved, Michael D., Michelle
			- [Building a Safe Penn State: Reporting Child Abuse](https://lrn.psu.edu/)  
				- Daved, Michael D., Hifzah 		

- 2016-09-13
	+ Attending - Rick, Andrea, Michael O., Michael D., Amber, Katie, Hifzah, Daved, Michelle, Alyssa, Shivani
	+ Agenda
		* Discuss 1st chapter 'An Introduction to Vision Science':  [gilmore-lab/references/Palmer-1999/palmer-1999-chap-1.pdf](https://psu.app.box.com/files/0/f/11123835210/Palmer-1999)
	+ Action Items
		* Read 2nd Chapter 'An Introduction to Vision Science': [gilmore-lab/references/Palmer-1999/palmer-1999-chap-2.pdf](https://psu.app.box.com/files/0/f/11123835210/Palmer-1999)
		* Write Biography in [Markdown Format](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and send to lab gmail account	
		* Required Training: Complete by 9/15/2016  
		  Send all Certificates of Completion to the lab gmail account
			- [Clery Act Training](https://lrn.psu.edu/)  
				- Daved, Michael D., Michelle, Hifzah  
			- [Building a Safe Penn State: Reporting Child Abuse](https://lrn.psu.edu/)  
				- Daved, Michael D., Hifzah  
			- [IRB CITI Training](https://citi.psu.edu/)  
				- Complete both Modules: Biomedical and Social Science  
				- Hifzah  	
- 2016-08-30
	+ Attending - Rick, Andrea, Daved, Michael O., Sam, Shivani, Michelle, Katie, Auburn, Alyssa, Hifzah
	+ Agenda
		* Overview of lab meetings and projects for the semester.
		* Required Training: Complete by 9/15/2016  
		  Send all Certificates of Completion to the lab gmail account
			- [Clery Act Training](https://lrn.psu.edu/)  
				- Daved, Sam, Shivani, Michael D., Michelle, Alyssa, Hifzah  
			- [Building a Safe Penn State: Reporting Child Abuse](https://lrn.psu.edu/)  
				- Daved, Sam, Shivani, Michael D., Alyssa, Hifzah  
			- [IRB CITI Training](https://citi.psu.edu/)  
				- Complete both Modules: Biomedical and Social Science  
				- Sam, Alyssa, Hifzah  			
			- Watch Epilepsy Video
				- Michael D. - Need to Schedule 
				- Katie, Auburn, Hifzah - Today 10:30am Room 449
				- Alyssa - Today after lab meeting Room 449
			- Background Check Completion Date
	+ Action Items
		* Send .pdf of completion certificates to the lab gmail account
		* Write Biography in [Markdown Format](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) and send to lab gmail account
		* Read 1st chapter 'An Introduction to Vision Science' - posted on box [gilmore-lab/references/Palmer-1999/palmer-1999-chap-1.pdf](https://psu.app.box.com/files/0/f/11123835210/Palmer-1999)
				
- 2016-08-23  
	+ Attending - Daved, Michael O., Sam, Shivani, Michelle, Katie, Auburn, Alyssa, Hifzah 
	+ Agenda  
		- Introductions
			- Andrea Seisler, Lab Manager
			- Returning Lab Members
				- Daved, Michael O., Sam, Shivani, Raya, Michael D. Michelle, Karina, Katie, Auburn  
			- New Lab Members: Alyssa and Hifzah  
		
		- Highlights of active projects  
			- Optic Flow  
				- [Infant motion coherence (MOCO) EEG](https://nyu.databrary.org/volume/146) - 7 more participants  
				- [Child motion form (MOFO) EEG](https://nyu.databrary.org/volume/144) - Analysis/Writing  
				- [Child motion form (MOCO) behavior](https://nyu.databrary.org/volume/218) - 1 more participant  
				- Infant motion statistics 
			- Symmetry  
				- Adults' sorting behavior - Analysis/Writing  
			- [Databrary](https://nyu.databrary.org/)      
						
		- Did everyone get their background clearances completed? These are required to participate in data collection. If not, please see Elaine Prestia (140 Moore) to see what you still need.  
		
		- Required Training: Complete by 9/15/2016 
		  Send all Certificates of Completion to the lab gmail account
			- [Clery Act Training](https://lrn.psu.edu/)  
				- Daved, Sam, Shivani, Michael D., Michelle, Alyssa, Hifzah  
			- [Building a Safe Penn State: Reporting Child Abuse](https://lrn.psu.edu/)  
				- Daved, Sam, Shivani, Michael D., Alyssa, Hifzah  
			- [IRB CITI Training](https://citi.psu.edu/)  
				- Complete both Modules: Biomedical and Social Science  
				- Sam, Alyssa, Hifzah  			
			- Watch Epilepsy Video
				- Michael D., Karina - Need to Schedule 
				- Katie, Auburn, Hifzah - 8/30 10:30am Room 449
				- Alyssa - 8/30 after lab meeting Room 449
				  
		- If you have trouble logging in for the Clery Act or Reporting Child Abuse Training, please email learning@psu.edu to have your account reset.
		
		- Gather Contact information: PSU ID, PSU email, email for calendar invitations, phone   
				
		- Lab participation  
			- Volunteer or Credit?  
				- If participating in lab for Credit, the psych 494 form must be signed by Dr. Gilmore and returned to the Psychology Advising Office (125 Moore) by Friday 8/26/2016 or you will be charged a late fee.  
			- How many hours per week?  
				- 2 credits = 6 hours  
				- 3 credits = 9 hours  
				
	+ Action Items  
	    - First students for paper assignments - Sam, Shivani, Alyssa, Hifzah  
	    - Interested in learning 
	        - coding (e.g. R, SPSS)
	        - MRI data collection/analysis
	        - post ideas for papers to discuss
	        				

### Spring 2016  

- 2016-03-29
	- Next meeting on 2016-04-12

- 2016-03-22
	- Agenda
		- Participants for AAC/DS project, email Emily Neumann, eeneumann3@gmail.com
		- Video coding project update
			- 8 to code; 5 complete. On moving/stationary pass.
			- Reliability coding on every 5th episode/segment.
			- Next step is pass on moving segments by locomotion type.
		- Next optic flow behavior pilot is on Friday.
		- Infant MOCO status
			- One last night. almost 8 mos. Another Friday.
		- Paper for next week? Michael and Jun will decide and post link to reference DOI.
		- Tools of the trade: git and GitHub, Markdown, Databrary, R/RStudio, Datavyu, Asana, Zotero, Box.

- 2016-03-15
	- Debrief about optic flow behavior pilot.
		- 4 year-old. Tried new lighting bar. Camera light a distraction. Need to mask. Andrea, Katie, Corinna, Daved, Raya.
		- Button pressing difficult. Need to try pointing. Revise explanatory language and review (ARS). Change battery halfway through. Rick would like to see video of protocol.
		  - Explanatory language for instructions[moco-3pat-psychophysics-participant-instructions](https://github.com/gilmore-lab/moco-3-pattern-psychophysics/blob/master/notes/moco-3pat-psychophysics-participant-instructions.md) updated on 2016-03-15 (ars)
	- Update about child MOFO analysis, and infant MOCO
		- Fesi et al 2011 and 2014 papers for image descriptions.
		- Rick and Andrea to meet at HEF to review.
	- Recruiting update.
		- Making calls MTWR.
		- Are recruiters saving spreadsheet properly? Need to revise protocol and procedure for downloading and uploading spreadsheet. Will review protocol next week.
		   - Excel is set up to Autosave every 5 minutes
		   - Updated protocol [Phone_Call_Scheduling_Procedure] (https://github.com/gilmore-lab/protocols/blob/master/Phone_Call_Scheduling_Procedure.md) on 2016-03-16 (ars)
	- Continued discussion of [symmetry sorting project](https://github.com/gilmore-lab/symmetry-sorting).
	- Discuss next week.
		- Update about **video coding project**.
		- Assign paper for week following.

- 2016-02-23
	- Discussion of Lee, D., & Seo, H. (2016). Neural Basis of Strategic Decision Making. Trends in Neurosciences, 39(1), 40–48. <https://doi.org/10.1016/j.tins.2015.11.002>. Daved, Michelle, and Michael O.
	- Next week: finish symmetry sorting project update and MOFO data analysis update.
- 2016-02-16
	- Rick discussed recent progress on symmetry sorting experiment.
- 2016-02-09
	- Discussed
		- Plot.ly
		- ReadCube
		- ResearchGate.net
	- For 2016-02-23
		- Read and discuss: Lee, D., & Seo, H. (2016). Neural Basis of Strategic Decision Making. Trends in Neurosciences, 39(1), 40–48. <https://doi.org/10.1016/j.tins.2015.11.002>. Daved, Michelle, and Michael O.
	- Future readings could be
		- Raichle, M. E. (2009). A brief history of human brain mapping. Trends in Neurosciences, 32(2), 118–126. <https://doi.org/10.1016/j.tins.2008.11.001>
		- Yang, J., Kanazawa, S., Yamaguchi, M. K., & Motoyoshi, I. (2015). Pre-constancy Vision in Infants. Current Biology, 25(24), 3209–3212. <https://doi.org/10.1016/j.cub.2015.10.053>
- 2016-02-02
	+ Agenda
		- [Innovations in Scholarly Communications Survey](https://innoscholcomm.typeform.com/to/JEx5CP?source=6s2a9G)
				- Assignment: Take survey; pick two tools you aren't familiar with and write a short paragraph about each of them.
		- Recruiting team assessment
- 2016-01-26
	+ Attending
	+ Agenda
		- MOCO/MOFO EEG
			- Weekly Monday 11:30-1; add to schedule
		- MOCO psychophysics child
			- Add project meeting to calendar (Andrea)
		- Symmetry sorting (Michelle)
		- Video data coding
			- Do reliability coding
			- Coders should review this site: <https://dx.doi.org/10.17910/B7988V>
- 2016-01-19
	+ Agenda
		* Need .md bios from some lab members
	+ Small Group Meeting Schedule
		* Child (MOCO) behavior - meetings 12:45-1:45 Thursdays
		* Video Coding - Meetings 10-11am Fridays or 11:15-12:15 Fridays
		* Infant motion coherence (MOCO) EEG - Everyone will participate in data collection sessions.
	+ Journals with articles potentially relevant to lab interests
		- [Nature](https://www.nature.com/neuro/index.html)
	    	- <https://www.nature.com/neuro/journal/vaop/ncurrent/full/nn.4214.html>
	    	- <https://www.nature.com/neuro/journal/v19/n1/full/nn.4179.html>
				- <https://www.nature.com/nrn/index.html>
		- [Nature Reviews Neuroscience](https://www.nature.com/nrn/journal/vaop/ncurrent/abs/nrn.2015.19.html)
			- <https://www.nature.com/nrn/journal/v17/n1/abs/nrn.2015.2.html>
		- [Journal of Neuroscience](https://www.jneurosci.org)
	    	- <https://www.jneurosci.org/content/36/2.toc.pdf>, p. 268, p. 432
		- [Neuron](https://www.cell.com/neuron/home)
	    	- <https://www.cell.com/neuron/abstract/S0896-6273(15)01120-4>
	     <https://www.cell.com/trends/cognitive-sciences/abstract/S1364-6613(15)00274-0>
		- [Trends in Neurosciences](https://www.cell.com/trends/neurosciences/home)
			- <https://www.cell.com/trends/neurosciences/abstract/S0166-2236(15)00281-7>
			- <https://www.cell.com/trends/neurosciences/abstract/S0166-2236(15)00248-9>
			- <https://www.cell.com/trends/neurosciences/abstract/S0166-2236(08)00265-8>
		- [Journal of Vision](https://jov.arvojournals.org/issues.aspx#issueid=934263)
			- <https://jov.arvojournals.org/article.aspx?articleid=2411821>
			- <https://jov.arvojournals.org/article.aspx?articleid=2436830>
		- [Vision Research](https://www.journals.elsevier.com/vision-research/)
			- <https://www.sciencedirect.com/science/article/pii/S0042698915003430>
			- <https://www.sciencedirect.com/science/article/pii/S004269891500334X>
		- [Trends in Cognitive Science](https://www.cell.com/trends/cognitive-sciences/home)
		- [Developmental Science](https://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-7687)
		- [Infancy](https://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1532-7078)
		- [Developmental Cognitive Neuroscience](https://www.journals.elsevier.com/developmental-cognitive-neuroscience/)
		- [Developmental Psychology](https://psycnet.apa.org/index.cfm?fa=browsePA.volumes&jcode=dev)
		- [Child Development](https://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-8624)  	
- 2016-01-12
	+ Attending
		* Daved, Michelle, Michael O., Michael D., Jun, Sam, Shivani, Andrea
	+ Agenda
		* Create Schedules for project meetings
		* Psych 494 forms gathered - have Rick sign and return forms
		* Set up initial small group meetings

### Fall 2015

- 2015-11-17
    + Agenda
        * Discuss Wattam-Bell, J., Birtles, D., Nyström, P., von Hofsten, C., Rosander, K., Anker, S., … Braddick, O. (2010). Reorganization of Global Form and Motion Processing during Human Visual Development. *Current Biology*, 20(5), 411–415. <https://doi.org/10.1016/j.cub.2009.12.020>
        * Discuss Braddick, O., Atkinson, J., & Wattam-Bell, J. (2011). Chapter 6 - VERP and brain imaging for identifying levels of visual dorsal and ventral stream function in typical and preterm infants. In J. A. and G. M. I. Oliver Braddick (Ed.), *Progress in Brain Research* (Vol. 189, pp. 95–111). Elsevier. <https://dx.doi.org/10.1016/B978-0-444-53884-0.00020-8>
- 2015-11-10
    + Agenda
        * Shivani leading discussion of Bourke, P., & Shaw, H. (2014). Spontaneous lucid dreaming frequency and waking insight. *Dreaming*, 24(2), 152–159. <https://doi.org/10.1037/a0036908>.
    + Attending
        * Rick, Raya, Andrea, Jun, Shivani, Michelle, Michael, Daved
- 2015-10-20
    + Agenda
        * Sam leads discussion of De Araujo, T. B., Silveira, F. R., Souza, D. L. S., Strey, Y. T. M., Flores, C. D., & Webster, R. S. (n.d.). Impact of video game genre on surgical skills development: a feasibility study. *Journal of Surgical Research*. <https://doi.org/10.1016/j.jss.2015.07.035>.
- 2015-10-13
    + Agenda
        * Rick discussing [Gilmore-Thomas-Fesi-2015 results](https://github.com/gilmore-lab/gilmore-thomas-fesi-2015), [Stimuli on Databrary](https://databrary.org/volume/75).
    + Attending
        * Michelle, Raya, Jun, Michael, Shivani
- 2015-10-06
    + Agenda
        * Jun leading discussion of Czerniak, S. M., Sikoglu, E. M., Navarro, A. A. L., McCafferty, J., Eisenstock, J., Stevenson, J. H., ... & Moore, C. M. (2014). A resting state functional magnetic resonance imaging study of concussion in collegiate athletes. *Brain imaging and behavior*, *9*(2), 323-332. <https://dx.doi.org/10.1007/s11682-014-9312-1>
    + Attending
        * Daved, Michelle, Rick, Jun, Shivani, Michael, Sam
- 2015-09-29
    + Attending
        * Michelle, Daved, Raya, Andrea, Jun
    + Agenda
        * Rick [presenting](https://rawgit.com/psu-psychology/developmental/master/prosem/2015-09-16-gilmore/dev-prosem-2015-09-16.html)
- September 22, 2015
    + Attending
        * Michelle, Raya, Rick, Daved, Sam, Andrea, Jun, Shivani
    + Agenda
        * Michelle's presentation
        * Training status
        * Discuss paper next week, Wattam-Bell et al. (2010). <https://dx.doi.org/10.1016/j.cub.2009.12.020>

- September 8, 2015
    + New meeting location in 444 Moore
        * Must leave by 8:50a.
    + Attending
        * Daved, Raya, Michelle, Rick, Michael, Sam, Shivani, Andrea
    + Agenda
        * Schedules
        * Training
        * Lab mtg presentations
    + Action items
        * Bios by next meeting, email to Andrea. Andrea has tutorial.
        * **No lab meeting next week, Tuesday 9/15**
        * Michelle will present on 9/22. Jun on 10/6. Shivani 11/10. Sam 10/20.
- September 1, 2015
    + Andrea will investigate (ask Elaine) moving meeting to 444 Moore.
    + Introductions
        * Andrea Seisler, Lab Manager
        * Sam Pai, 3 credits 494
        * Daved Fouad
        * Raya Willoughby, 2 credits 494
        * Shivani Patel
        * Jun Oh
        * Michael O'Neill
    + Highlights of active projects
        * Optic Flow
            - Infant motion coherence (MOCO) EEG
            - Child motion form (MOFO) EEG
            - Child motion form (MOCO) behavior
            - Infant motion statistics
        * Symmetry
            - Adults' sorting behavior
        * Databrary
    + Action items
        * Clery Act training (Andrea will send link).
        * Get added to psubrainlab Google calendar (send Andrea your email).
        * Register for PSYCH 494 credit.
        * Watch epilepsy video in lab.

### Spring 2015

- [January 22, 2015](https://github.com/gilmore-lab/mtg-minutes/blob/master/2015-01-22.md)  
- January 29, 2015
    - Jun, William, Michael, Sam and Rick attended.
    - Jun will lead a discussion of the following paper: Irimia, A., Goh, S.-Y. M., Torgerson, C. M., Stein, N. R., Chambers, M. C., Vespa, P. M., & Van Horn, J. D. (2013). Electroencephalographic inverse localization of brain activity in acute traumatic brain injury as a guide to surgery, monitoring and treatment. Clinical Neurology and Neurosurgery, 115(10). [https://dx.doi.org/10.1016/j.clineuro.2013.08.003](https://dx.doi.org/10.1016/j.clineuro.2013.08.003)
    - Discussed using Markdown for student bios. [Markdown Help](https://help.github.com/articles/markdown-basics/).
    - Discussed [logo contest](https://app.asana.com/0/24984362312919/24984362312933).
- February 5, 2015
    - Jun, Michael, Shivani, Andrea, Rick
    - Discussed bios on GitHub, child abuse reporting training, lab photo scheduling, epilepsy video.
- February 12, 2015
    + Sam, Jun, Michael, William, Shivani, Andrea, Rick
    - Sam will present the following paper: Dawson, N., Morris, B. J., & Pratt, J. A. (2015). Functional brain connectivity phenotypes for schizophrenia drug discovery. Journal of Psychopharmacology, 29(2), 169–177. [doi:10.1177/0269881114563635](https://jop.sagepub.com/content/29/2/169.full)
    - **Rick will be out next week**
- February 19, 2015 - No Meeting this Week
- February 26, 2015
- March 5, 2015 - No Meeting this Week
- March 19, 2015  
- March 26, 2015  
- April 2, 2015  
- April 9, 2015  
- April 16, 2015  
- April 23, 2015 - End of semester celebration at The Waffle Shop
- April 30, 2015 - No Meeting!
