---
<<<<<<< HEAD
Title: who-we-are
=======
Title: Who-we-are
>>>>>>> 2ce4a552f5bf7f4a030e7934c642b2022f9fe0ad
---
## Gilmore Bio

Rick O. Gilmore is Associate Professor of Psychology, a Huck Institute of the Life Sciences faculty member, and an Associate of the Institute for Cyberscience. He earned his bachelor's degree *magna cum laude* in Cognitive Science from [Brown University](http://www.brown.edu), and master's and doctoral degrees in Psychology from [Carnegie Mellon University](http://www.cmu.edu) where he participated in the [Center for the Neural Basis of Cognition (CNBC)](http://cnbc.cmu.edu) training program in cognitive neuroscience. Gilmore's research focuses on the development of visual perception and memory. He is particularly interested in the development of brain networks that enable perceivers to extract information about the layout of the environment, the shape of objects, and the speed and direction of self-movement from patterns of visual motion called optic flow. Gilmore is also keenly interested in developing tools and practices that make scientific research more open, transparent, and reproducible. He is co-founder and Co-Director of the [Databrary.org](http://databrary.org) data library.

From 2008 to 2014, Gilmore served as the founding Director of Human Imaging at Penn State's Social, Life, and Engineering Sciences Imaging Center [(SLEIC)](http://imaging.psu.edu). He has won the College of the Liberal Arts tenure-line faculty teaching award, leads the Human Developmental Neuroscience Initiative for the Child Study Center, and has had support for his research from the National Institutes of Health and the National Science Foundation. Gilmore has served as president of the [Centre Region Bicycle Coalition](http://centrebike.org), the [Acoustic Brew Concert Series](http://acousticbrew.org), and the [State College Community Theatre](http://scctonline.org).

## Contact Information

<p>114 Moore Building<br/>
Department of Psychology<br/>
The Pennsylvania State University<br/>
University Park, PA 16801<br/>
814-865-3664, voice <br/>
814-863-7002, fax<br/>

rogilmore AT-SIGN psu DOT edu<br/>

<a href="http://www.personal.psu.edu/rog1">http://www.personal.psu.edu/rog1</a></br>

# For Students

The Brain Development Lab, part of the [Psychology Department](http://psych.la.psu.edu) at Penn State, is looking for research assistants to study brain development in infants, children, and adolescents for **Spring 2018**. You can earn research project (PSY 494) credit or work study funds, and learn video, computer, and communication skills. Prior research experience and computer skills are a plus, but aren't required. We are especially interested in students who have morning availability, computer skills, or are interested in developing skills in advertising, marketing, or public relations. You may apply by completing an [application](https://docs.google.com/forms/d/1HgafpfTVPyMk_Wzf4b_ubzig_fs4lFGS6qh_y0sa0uE/viewform).

## Current Staff

### [Andrea Seisler](mailto:ars17psu@gmail.com), Lab Manager
Andrea R. Seisler is the Laboratory Manager of the Brain Development Laboratory directed by Dr. Rick O. Gilmore. She received her bachelor's and master's degree in Biomedical Engineering from [The Catholic University of America](http://www.cua.edu/). During her graduate studies, she was a recipient of the [Clare Booth Luce Fellowship](http://www.hluce.org/cblprogram.aspx) award.

She completed MRI based neuroscience and orthopedics research while working at [The National Institutes of Health](http://www.nih.gov/) from 2001-2007. After her move to State College, she served as an IRB Compliance Coordinator for the [Office for Research Protections](http://www.research.psu.edu/orp/humans) at Penn State and then moved on to manage the Human Electrophysiology Facility located at the [Social, Life, and Enginineering Sciences Imaging Center](http://www.imaging.psu.edu/) through 2014.

#### Contact Information

<p>503 Moore Building<br/>
Department of Psychology<br/>
The Pennsylvania State University<br/>
University Park, PA 16802<br/>
ars17 AT-SIGN psu DOT edu</p>


### Alyssa Pandos, Undergraduate Student  

Alyssa is an undergraduate student pursuing a degree in Psychology with a concentration in Neuroscience and a minor in Biology. She plans on graduating in the spring of 2018. After graduation, her ultimate goal is to further her education by obtaining a PhD in a field of Neuroscience or Neuropsychology. 

### Charmi Mehta, Undergraduate Student  

I am an Undergraduate student pursuing a [degree in Psychology with Neuroscience option](http://psych.la.psu.edu/). My interests are spread out across many different domains such as coding, neuroscience, medicine, and art. I intend to combine all of my interests in the future to help further scientific research. After graduating in Spring 2018, I intend to apply to medical school and concentrate in anesthesiology.

<!-- ### Hifzah Malik, Undergraduate Student   -->

<!-- Hifzah is a junior majoring in BioBehavioral Health and is minoring in Psychology at Pennsylvania State University. She plans on going to PA school after graduation to become a physician assistant. -->

<!-- Other than social science, she also spends her time taking part in the [She's the First](https://www.shesthefirst.org/campus-chapters/) club which focuses on fundraising money to provide education for girls in third world countries.  -->

### Michael Dexheimer, Undergraduate Student

Michael is majoring in [Engineering Science](http://www.esm.psu.edu/) at The Pennsylvania State University. He is working to improve his understanding of research and technology in neuroscience.

After graduating in the spring of 2018 Michael intends to further his education in medical school, where he will combine his interests in Engineering, Neuroscience, and Medicine. 

### Sarah Shahriar
Sarah is a junior majoring in Psychology with a concentration in Neuroscience. She hopes to pursue a medical degree after studying at Penn State University and hopes to practice as a psychiatrist in the future. 

Sarah is originally from Hershey, PA and enjoys spending her time volunteering at Penn State Hershey Medical Center Children’s Hospital within the Ronald McDonald charities. 

## Recent Alumni

- Raya Willoughby
- Katie Torres
- Shivani Patel
- Michael O'Neill, Graduate student, PSU
- Daved Fared
- Auburn Lattanzio
- Michelle Shade
- Sam Pai
- Jun Oh, Apprentice Ruby on Rails Developer, Launch Academy, Inc.
- Amanda Thomas, Postdoctoral researcher, Swarthmore
- William Adamiak, NIH IRTA
- Shivam Vedak, Medical student
- Dan Elbich, Graduate student, Penn State
- Jeremy Fesi, Ph.D., Postdoctoral Scientist, CUNY
- Lorena Gonzalez, Graduate student, Penn State
- Ricky Groner, IT Support Specialist, Huck Institutes of the Life Sciences, Penn State
- Ken Hwang, Consultant, Anexinet
- Matthew Lee, MBA student, Penn State
- Patricia Jones, Optometry student, Pennsylvania College of Optometry
