---
Title: who-we-are
---
## For Interested Students

The Brain Development Lab, part of the [Psychology Department](http://psych.la.psu.edu) at Penn State, is looking for research assistants to study brain development in infants, children, and adolescents for **Fall 2019**. You can earn research project (PSY 494) credit or work study funds, and learn video, computer, and communication skills. Prior research experience and computer skills are a plus, but aren't required. We are especially interested in students who have morning availability, computer skills, or are interested in developing skills in advertising, marketing, or public relations. You may apply by completing an [application](https://docs.google.com/forms/d/1HgafpfTVPyMk_Wzf4b_ubzig_fs4lFGS6qh_y0sa0uE/viewform).

## Lab Director

Rick O. Gilmore is Associate Professor of Psychology, a Huck Institute of the Life Sciences faculty member, and an Associate of the Institute for Cyberscience. He earned his bachelor's degree *magna cum laude* in Cognitive Science from [Brown University](http://www.brown.edu), and master's and doctoral degrees in Psychology from [Carnegie Mellon University](http://www.cmu.edu) where he participated in the [Center for the Neural Basis of Cognition (CNBC)](http://cnbc.cmu.edu) training program in cognitive neuroscience. Gilmore's research focuses on the development of visual perception and memory. He is particularly interested in the development of brain networks that enable perceivers to extract information about the layout of the environment, the shape of objects, and the speed and direction of self-movement from patterns of visual motion called optic flow. Gilmore is also keenly interested in developing tools and practices that make scientific research more open, transparent, and reproducible. He is co-founder and Co-Director of the [Databrary.org](http://databrary.org) data library.

From 2008 to 2014, Gilmore served as the founding Director of Human Imaging at Penn State's Social, Life, and Engineering Sciences Imaging Center [(SLEIC)](http://imaging.psu.edu). He has won the College of the Liberal Arts tenure-line faculty teaching award, leads the Human Developmental Neuroscience Initiative for the Child Study Center, and has had support for his research from the National Institutes of Health and the National Science Foundation. Gilmore has served as president of the [Centre Region Bicycle Coalition](http://centrebike.org), the [Acoustic Brew Concert Series](http://acousticbrew.org), and the [State College Community Theatre](http://scctonline.org).

#### Contact Information

<p>114 Moore Building<br/>
Department of Psychology<br/>
The Pennsylvania State University<br/>
University Park, PA 16801<br/>
814-865-3664, voice <br/>
814-863-7002, fax<br/>

rogilmore AT-SIGN psu DOT edu<br/>

<a href="http://www.personal.psu.edu/rog1">http://www.personal.psu.edu/rog1</a></br>

## Current Staff

### [Andrea Seisler](mailto:ars17psu@gmail.com), Lab Manager
Andrea R. Seisler is the Laboratory Manager of the Brain Development Laboratory directed by Dr. Rick O. Gilmore. She received her bachelor's and master's degree in Biomedical Engineering from [The Catholic University of America](http://www.cua.edu/). During her graduate studies, she was a recipient of the [Clare Booth Luce Fellowship](http://www.hluce.org/cblprogram.aspx) award.

She completed MRI based neuroscience and orthopedics research while working at [The National Institutes of Health](http://www.nih.gov/) from 2001-2007. After her move to State College, she served as an IRB Compliance Coordinator for the [Office for Research Protections](http://www.research.psu.edu/orp/humans) at Penn State and then moved on to manage the Human Electrophysiology Facility located at the [Social, Life, and Enginineering Sciences Imaging Center](http://www.imaging.psu.edu/) through 2014.

#### Contact Information

<p>503 Moore Building<br/>
Department of Psychology<br/>
The Pennsylvania State University<br/>
University Park, PA 16802<br/>
ars17 AT-SIGN psu DOT edu</p>

### Yiming Qian, Graduate Student

Yiming is the graduate student in the Department of Psychology at PSU. Her research interests is exploring the development of brain networks from early childhood to adulthood, using multimodal neuroimaging tools. She is also interested in the mechanism of visual motion. Here is her [schedule](https://rstudio-connect.tlt.psu.edu:3939/content/22/projects_scheme.html) for the current research projects.

Besides research activities, Yiming enjoys reading, cooking, gardening, hiking and fishing. She is a big fan of operas and musicals.

### Ashton Dluzneski, Undergraduate Student 

Ashton Dluzneski is a senior at Penn State majoring in Psychology with a Neuroscience specificity. She is originally from the Philadelphia area. She has a passion for all animals and has been riding horses since she was five years old.  She also volunteers at [Sebastian Riding Center](http://sebastianriding.org), a farm specialized in educating intellectually and developmentally disabled children and adults about riding and caring for horses. Her family also breeds Newfoundland dogs, often using them as therapy dogs to help at risk youth. 

When she graduates, Ashton hopes to further her studies in the field of neuroscience, and eventually work in a research lab that studies neurodegenerative disorders.

### Michelle Mendez, Undergraduate Student 

Michelle Mendez is a sophomore majoring in Psychology. She is still contemplating on whether she wants to pursue a Neuroscience concentration or a Life Sciences concentration. She is from the city of Philadelphia where she spent most summers volunteering at a local recreational center. She is interested in adolescents and how they develop. She also has a great interest in mental illness, what causes it to develop, and how one can minimize the effects. 

She plans on furthering her research experience over the next few years, and plans on attending graduate school after she graduates.

### Sandy Rayes, Undergraduate Student 

Sandy is a junior double majoring in Biology and Psychology. She is active on campus as a previous orientation leader, membership director for [Blue and White Society](http://www.bluewhitesociety.com), and [THON](https://thon.org) captain. Additionally, Sandy started a new club, We Are The World, which celebrates the diverse culture at Penn State Altoona. Sandy plans to attend medical school after her graduation in May of 2020.

### Sarah Shahriar, Undergraduate Student 

Sarah S. Shahriar is a senior majoring in Psychology with a concentration in Neuroscience. She is the President of [University Park’s Psi Chi Chapter](http://sites.psu.edu/psichi/), The International Psychology Honors Society. 

She is originally from Hershey, PA and enjoys volunteering her time working with special education students at [LifeLink](https://lifelinkpsu.weebly.com/) on campus. After she graduates, Sarah intends to pursue a M.D. to practice psychiatry in the future.

### Zhichun Zhao, Undergraduate Student 

I am a junior student majoring in Psychology with a concentration in Life Science. I am originally from Penn State Harrisburg where I started a film editing club. I also hold great interest in interactive design and participated in several workshops in Copenhagen over the summer. People who might be interested can check the website [here](http://ciid.dk/education/summer-school/).
I plan to pursue a graduate’s degree after I graduate. I hope to carry my knowledge of psychology into whatever field I will be working on in the future. 


## Recent Alumni

- Alyssa Pandos  
- Charmi Mehta  
- Michael Dexheimer 
- Hifzah Malik
- Raya Willoughby
- Katie Torres
- Shivani Patel
- Michael O'Neill, Graduate student, PSU
- Daved Fared
- Auburn Lattanzio
- Michelle Shade
- Sam Pai
- Jun Oh, Apprentice Ruby on Rails Developer, Launch Academy, Inc.
- Amanda Thomas, Postdoctoral researcher, Swarthmore
- William Adamiak, NIH IRTA
- Shivam Vedak, Medical student
- Dan Elbich, Graduate student, Penn State
- Jeremy Fesi, Ph.D., Postdoctoral Scientist, CUNY
- Lorena Gonzalez, Graduate student, Penn State
- Ricky Groner, IT Support Specialist, Huck Institutes of the Life Sciences, Penn State
- Ken Hwang, Consultant, Anexinet
- Matthew Lee, MBA student, Penn State
- Patricia Jones, Optometry student, Pennsylvania College of Optometry
