project:
  type: website
  output-dir: "../docs"
  render:
    - "*.qmd"
    - "posts/*.qmd"
    - "lab-mtg-talks/*.qmd"
  
execute: 
  freeze: auto

website:
  title: "BBD Lab"
  navbar:
    left:
    - text: "Research"
      href: research.qmd
    - text: "Publications"
      href: publications.qmd
    - text: "For Parents"
      href: parents.qmd
    # - text: "Participants"
    #   href: participants.qmd
    - text: "Who we are"
      href: who-we-are.qmd
    - text: "Lab mtgs"
      menu: 
        - text: "Current semester"
          href: lab-meetings.qmd
        - text: "Past semesters"
          href: lab-meetings-archive.qmd
    - text: "Resources"
      href: resources.qmd
    - text: "Site info"
      href: site-info.qmd
    right:
        - icon: github
          text: Github
          href: https://github.com/gilmore-lab/
format:
  html:
    theme: default
    date-modified: last-modified
    bibliography: [bib/lab.bib]
    csl: bib/apa.csl
    html-math-method: mathjax
