---
title: "Lab meeting archive"
bibliography: "bib/lab.bib"
---
## Fall 2024

For the Fall 2024 Semester, we will meet on Thursdays 8:00-8:50 am in room 444 Moore.

### Thursday, November 14, 2024 

### Thursday, November 7, 2024 - 503 Moore

1. [Visual Acuity](https://gilmore-lab.github.io/visual-acuity/) Project - Paper analysis work session
  - [Visual Acuity Analysis Procedure](https://docs.google.com/document/d/1jdoIzE1cLHphA9y89jyhK20lTXJ2WCu4fBIATH25EeY/edit?tab=t.0)
  - [Legacy Project Acuity Data: By Paper](https://docs.google.com/spreadsheets/d/1UFZkbh9oU4JHpYsrkDQcNmDyqD4J-qB74dhyMzIkqKs/edit?gid=432255138#gid=432255138)
  - [Legacy Project Data Analysis](https://docs.google.com/spreadsheets/d/1XnGweqEAiTlU8mhvWqtCCMNm9l5txdR0YpQsuMxvgio/edit?gid=998401983#gid=998401983)

### Thursday, October 31, 2024 - 503 Moore

1. [Visual Acuity](https://gilmore-lab.github.io/visual-acuity/) Project - Paper analysis training session

### Thursday, October 24, 2024

1. Discuss @Franconeri2021-uv and look at data visualizations provided by lab members.
2. Catch up on Training/Biography/Datacamp Status

### Thursday, October 17, 2024

0. Attending
  - Andrea, Brianna, Nicole, Julia, Lina, Hayley, Kassandra, Megan, Trinity 
1. Watched and discussed some of [Thinking with Data Visualizations, Fast and Slow](https://www.youtube.com/watch?v=OdHLpZQF-Zs) 
2. To Do 
  - Read [@Franconeri2021-uv] and be prepared to discuss on 10/24.
  - Bring at least 2 data visualizations that you want to talk about.
  - Create a [Datacamp](https://www.datacamp.com/) account with your psu email account and accept the invitation to the  **PSY 494** space if you have not already
  - Continue working on required training:  [Instructions](https://gilmore-lab.github.io/protocols/trainings.html)


### Thursday, October 10, 2024

0. Attending
1. Data visualization paper journal club on [@Franconeri2021-uv].
  - Bring at least 2 data visualizations that you want to talk about.
  - Discussion [notes](lab-mtg-talks/franconeri-etal-2021.qmd) from Spring 2024

2. Biography status

### Thursday, October 3, 2024

0. Attending
- Andrea, Lina, Hayley, Gavin, Nicole, Brianna, Trinity, Megan, Bruna, Kassandra
1. Learn R using [Datacamp](https://www.datacamp.com/) 
  - First Assignment Introduction to R - Due 10/10
  
2. Training new/returning lab members [Instructions](https://gilmore-lab.github.io/protocols/trainings.html)
 - CITI, Clery Act, Reporting Suspected Child Abuse, Compliance Training, Title IX
3. Write Biographies use [Markdown Cheatsheet create links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)
4. ARS To Do
- send all lab members links to Datacamp

### Thursday, September 26, 2024

0. Attending
1. Legacy Project discussion
2. Brief DataCamp Discussion
  - was group approved?
3. Need volunteers for
  - update text of [BBD Lab Parent Page](https://gilmore-lab.github.io/parents.html) to reflect PLAY study

### Thursday, September 19, 2024 - CANCELLED

### Thursday, September 12, 2024

0. Attending
  - Andrea, Brianna, Bruna, Hayley, Lina, Gavin, Nicole, Paige, Julia, Trinity
1. Project updates
  - PLAY
2. [Onboarding and Training](https://gilmore-lab.github.io/protocols) and orientation (Andrea)
3. Need volunteers for
  - Lab meeting scribe
  - Lab blogger
4. Plans for next two weeks

### Thursday, September 5, 2024

0. Attending
  - Julia, Bruna, Hayley, Gavin, Brianna, Trinity, Nicole, Paige, Lina
1. Introductions
2. Orientation to Fall 2024 lab priorities (Rick)
    - Play & Learning Across a Year (PLAY) Project, [PLAY site](https://play-project.org), [Parent site](https://anhourinthelife.org), [KoBoToolbox Surveys](https://PLAY-behaviorome.github.io/KoBoToolbox/)
        - Data Collection Update (Paige, Brianna)
    - Legacy Project, especially [Visual Acuity](https://gilmore-lab.github.io/visual-acuity/)
    - [Databrary](https://databrary.org), especially the [Databrary Guide](https://databrary.github.io/guide), the [*databraryr* package](https://databrary.github.io/databraryr), and the [Databrary Analytics](https://databrary.github.io/analytics).
    - Refreshing internal resources, especially the [lab website](https://gilmore-lab.github.io) and our lab [protocols site](https://gilmore-lab.github.io/protocols).
3. [Onboarding and Training](https://gilmore-lab.github.io/protocols) and orientation (Andrea)
4. Schedule

## Spring 2024

For the Spring 2024 Semester, we will meet on Tuesdays 8:00-8:50 am in room 444 Moore.

### Tuesday, April 23, 2024

- No meeting; Election Day

### Tuesday, April 16, 2024

- Attending: Andrea, Rick, Belle, Trinity
- Plan lab breakfast
- Yiming presentation (tentative)

### Tuesday, February 20, 2024

1. Brianna & Rick `ggplot2`
  - Assignment: Install (or update) [RStudio](https://posit.co/download/rstudio-desktop/).
  - [Choosing a chart type](https://guides.lib.berkeley.edu/data-visualization/type)
  - See also [@Cleveland1985-vu; @Franconeri2021-uv; @Friel2001-st].
2. Datacamp check-in

### Tuesday, February 13, 2024

::: {.callout-warning}

Cancelled because of bad weather

:::

1. Brianna & Rick `ggplot2`
  - Assignment: Install (or update) [RStudio](https://posit.co/download/rstudio-desktop/).
2. Datacamp check-in

### Tuesday, February 6, 2024

0. Attending
  - Rick, Bruna, Julia, Molly, Belle, Brianna, Paige, Andrea, Nicole
1. Announcements
  - Weekly lab times: Tue 9-11 (Molly, Julia, Paige, Liu, Belle), Thu 10:30-12 (Brianna, Julia, Bruna), Fri 11-1 (Nicole, Peter, Bruna, Brianna?)
2. Belle (& Rick) presentation/discussion of: 

Soska, K. C., Xu, M., Gonzalez, S. L., Herzberg, O., Tamis-LeMonda, C. S., Gilmore, R. O. & Adolph, K. E. (2021). (Hyper)active data curation: A video case study from behavioral science. *Journal of Escience Librarianship*, *10*(3). <https://doi.org/10.7191/jeslib.2021.1208>.

[Quarto slides](lab-mtg-talks/soska-etal-2021.qmd)

### Tuesday, January 30, 2024

0. Attending
  - Rick, Belle, Brianna, Andrea, Paige, Molly, Liu, Peter
  - Bruna, Julia, Yiming, Nicole (unable to attend) 
1. Datacamp check-in
2. Confirm team work schedule
  - Tue 9-11; Thu 10:30-12; Fri 11-1
3. Peter paper presentation

### Tuesday, January 23, 2024

0. Attending
  - Nicole, Belle, Julia, Bruna, Liu, Andrea, Yiming, Rick, Peter
1. Status Report
   - [Datacamp](https://www.datacamp.com/)
   - [PLAY](https://play-project.org/) update
      - recruitment
      - data collection
   - [Legacy Project: Visual Acuity](https://gilmore-lab.github.io/visual-acuity/)
2. Schedule Outstanding Lab Member Presentations from last semester
   - `ggplot2` interactive (Brianna, Rick) demo?
   - Peter paper discussion?
3. Missing Webpage Biography
   - Molly, Julia, Bruna

### CANCELLED ~~Tuesday, January 16, 2024~~

1. Status Report
   - [Datacamp](https://www.datacamp.com/) 
   - [PLAY](https://play-project.org/) update
      - recruitment
      - data collection
   - [Legacy Project: Visual Acuity](https://gilmore-lab.github.io/visual-acuity/)
2. Schedule Outstanding Lab Member Presentations from last semester
   - `ggplot2` interactive (Brianna, Rick) demo?
   - Peter paper discussion?
3. Missing Webpage Biography
   - Molly, Julia, Bruna

## Fall 2023

### Monday, December 11, 2023

- End of semester lab breakfast, [The Waffle Shop, 364 E. College Avenue](https://www.facebook.com/waffleshopdowntown).

### Tuesday, December 5, 2023

- Julia will lead a discussion of a paper: [@Courage1990-xe].
  - Link to Legacy Project: Acuity [dataset](https://docs.google.com/spreadsheets/d/1UFZkbh9oU4JHpYsrkDQcNmDyqD4J-qB74dhyMzIkqKs/edit#gid=0).
- ~~`ggplot2` interactive (Brianna, Rick) demo~~.
- *Attendees*: Julia, Liu, Madison, Belle, Briana, Yiming, Rick, Andrea
  
### Tuesday, November, 28, 2023 **CANCELLED**

- Julia will lead a discussion of a paper.
- Peter will lead a discussion of a paper:

### Tuesday, November 14, 2023

- Status report on DataCamp.</br>
- Schedule end of semester breakfast.
- PLAY status (Madison & Belle).
- Liu will discuss his work on the [Databrary Guide](https://databrary.github.io/guide) and how using ChatGPT has been helpful to that work.
- [Legacy Project: Visual Acuity](https://gilmore-lab.github.io/visual-acuity/) update (Rick, Brianna, Julia, Nicole, Peter).

### Tuesday, November 7, 2023

**No lab meeting**

### Tuesday, October 31, 2023

- Read and discuss this piece: <https://www.nytimes.com/interactive/2023/10/16/us/census-race-ethnicity.html>

### Tuesday, October 24, 2023

- Add [PDF](pdfs/huang-p-2023-10-17.pdf) and reference to paper [@Birch2022-rs] discussed last week.
- Practice visualizations of ruler reaction time data.

### Tuesday, October 17, 2023

1. Peter will lead a discussion of Birch, E. E., Hudgins, L. A., Jost, R. M., Cheng-Patel, C. S., Morale, S. E. & Kelly, K. R. (2022). Web-based visual acuity testing for children. *Journal of AAPOS: The Official Publication of the American Association for Pediatric Ophthalmology and Strabismus / American Association for Pediatric Ophthalmology and Strabismus*, *26*(2), 61.e1–e61.e5. <https://doi.org/10.1016/j.jaapos.2021.11.007>. [PDF](pdfs/huang-p-2023-10-17.pdf).
2. Watch video(s) from <https://mgto.org/meta-analysis-registered-reports/> on meta-analyses and registered reports.

### Tuesday, October 10, 2023

1. Project updates/work session
     - [Legacy Project: Visual Acuity](https://gilmore-lab.github.io/visual-acuity/). update (Rick, Brianna, Julia, Nicole, Peter)
2. Using R, R Markdown & Quarto (Rick & Andrea)
    - Planning
      - Goals
      - Are data sensitive or not
    - Create repo
    - Create RStudio project
    - Create stub site/documents
    - On data page
      - Purpose
      - Gathering
      - Cleaning
      - Visualization
    - Commit (& usually push)
    - Here is the page we generated: <https://gilmore-lab.github.io/ruler-reaction-time/>
3. Announcement
    - Next week (2023-10-17) Peter will lead a discussion of Birch, E. E., Hudgins, L. A., Jost, R. M., Cheng-Patel, C. S., Morale, S. E. & Kelly, K. R. (2022). Web-based visual acuity testing for children. *Journal of AAPOS: The Official Publication of the American Association for Pediatric Ophthalmology and Strabismus / American Association for Pediatric Ophthalmology and Strabismus*, *26*(2), 61.e1–e61.e5. <https://doi.org/10.1016/j.jaapos.2021.11.007>.

### Tuesday, October 3, 2023

**No lab meeting**

### Tuesday, September 26, 2023, 350 Moore

1. Project updates
    - [PLAY](https://play-project.org/) update (Madison, Andrea, Belle, Oriana)
    - [Legacy Project: Visual Acuity](https://gilmore-lab.github.io/visual-acuity/). update (Rick, Brianna, Julia, Nicole, Peter)
    - Databrary [Guide](https://databrary.github.io/guide/) project update (Andrea, Liu)
    
### Tuesday, September 19, 2023, 350 Moore
2. Looking for:
    - Web site master
    - [`databraryr`](https://databrary.github.io/databraryr) package tester and help with documentation.
    - Sign-up for Hypothes.is
3. Future meetings
    - Readings related to PLAY, visual acuity project, Databrary
        - Peter will look at: Teller, D. Y., McDonald, M. A., Preston, K., Sebris, S. L. & Dobson, V. (1986). Assessment of visual acuity in infants and children: The acuity card procedure. *Developmental Medicine and Child Neurology*, *28*(6), 779–789. As candidate for reading as a group. https://doi.org/10.1111/j.1469-8749.1986.tb03932.x
    - Work sessions on using Quarto and R Studio.
    - Learning Mermaid and Graphviz tools from [Quarto](https://quarto.org/docs/authoring/diagrams.html).

### Tuesday, September 12, 2023, 350 Moore

1. What is [PLAY](https://play-project.org/)? (Madison)
2. Introducing the Legacy Project: Visual Acuity (Rick)

### Tuesday, September 5, 2023, 350 Moore

1. Assigning work teams (Andrea)
2. Watch 

NYU Health Sciences Library. (2013, 13. November). Data Sharing and Management Snafu in 3 Short Acts (Higher Quality). Youtube. https://www.youtube.com/watch?v=66oNv_DJuPc

3. Discuss project team assignments (Rick)

### Tuesday, 8/29/2023, 350 Moore

1. Introductions
2. Orientation to Fall 2023 lab priorities (Rick)
    - Play & Learning Across a Year (PLAY) Project, [PLAY site](https://play-project.org), [Parent site](https://anhourinthelife.org), [KoBoToolbox Surveys](https://PLAY-behaviorome.github.io/KoBoToolbox/)
    - Legacy Project, especially [Visual Acuity](https://gilmore-lab.github.io/visual-acuity/)
    - [Databrary](https://databrary.org), especially the [Databrary Guide](https://databrary.github.io/guide), the [*databraryr* package](https://databrary.github.io/databraryr), and the [Databrary Analytics](https://databrary.github.io/analytics).
    - Refreshing internal resources, especially the [lab website](https://gilmore-lab.github.io) and our lab [protocols site](https://gilmore-lab.github.io/protocols).
3. [Onboarding and Training](https://gilmore-lab.github.io/protocols) and orientation (Andrea)
4. Schedule

## Goals

- Data science
    - Learn R on [Datacamp](https://www.datacamp.com/)
      - ggplot
      - Data wrangling with dplyr
    - Begin by creating or updating your a brief biography for the [Who we are](https://gilmore-lab.github.io/who-we-are.html) page on the lab website.
- Start preparing for presentations in Spring 2024
    - Train on poster template for R [posterdown](https://github.com/brentthorne/posterdown)
    - Submit abstracts for poster presentation:
  - [Undergraduate Research Exhibition](https://urfm.psu.edu/programs/undergraduate-exhibition#paragraphs-id-114)
  - [Psi Chi Research Conference](https://sites.psu.edu/psichi/research-conference-2/)
- Launch new projects
    - PLAY
        - Data collection
        - Locomotion coding
    - Legacy: Visual Acuity
    - ~~Migrate lab site to Quarto~~
- Reinvigorate old projects
    - Databrary tagging
    - Databrary User [Guide](https://databrary.github.io/guide)
    - ~~Testing and documenting [*databraryr* package](https://databrary.github.io/databraryr)~~
    - Test and enhance [Databrary Analytics](https://databrary.github.io/analytics)
    - [Motion meta-analysis](https://github.com/gilmore-lab/motion-metaanalysis)
- Future readings
  - Yiming's Ph.D. paper and paper reviews

## Previous meeting notes

[Notes from previous semesters](lab-meetings-previous.html)

## Helpful Links

- Global Protect Instructions for [Mac](https://ithelp.ssri.psu.edu/penn-state-vpn-mac) and [Windows](https://ithelp.ssri.psu.edu/penn-state-vpn)
<!-- - Click to login to our [R Studio Server space](https://rstudio.tlt.psu.edu/s/e40b8122db8f5ab27456f/) -->
- Click to login to [Datacamp](https://www.datacamp.com/)
- How to take screen shots for [Mac](https://support.apple.com/en-us/HT201361) and [Windows](https://www.howtogeek.com/226280/how-to-take-screenshots-in-windows-10/)
- [Databrary](https://www.databrary.org)

