---
title: Lab meetings
bibliography: "bib/lab.bib"
---

## Spring 2025

For the Spring 2025 Semester, we will meet on Fridays 8:00-8:50 am in room 444 Moore.

### Friday, February 21, 2025

0. Attending
1. Visual Acuity Update
2. Julia Present [@Palmer2005-qb]

### Friday, February 14, 2025

0. Attending
1. Paige Present: [@Thunstedt2022-qa]
2. Visual Acuity Update
- almost done with source
3. Accept invitation to [DataCamp](https://www.datacamp.com/) sent to your PSU email address - Bri, Gavin, Brianna, Bruna
4. Poster Presentation Opportunities
  - [Psi Chi](https://sites.psu.edu/psichi/), the International Honor Society in Psychology, is hosting its annual  [Spring Research Conference](http://sites.psu.edu/psichi/research-conference-2/) in April.
    - 2/21: Submit [application](https://forms.gle/UGqftFVr9daYMAKy8) at 11:59pm
    - 4/23: 1:30-4:30pm In-person Conference, Moore Atrium
    - 4/23: 6:00 -7:00pm Virtual Conference, Zoom
  - The [Undergraduate Exhibition](https://urfm.psu.edu/programs/undergraduate-exhibition) is in April
    - 2/24: application will be available
    - 3/17: application due date
    - 4/14-16: Virtual Exhibition
    - 4/16: 11am-1pm In-Person Poster Presentation, Alumni Hall, HUB
    - 4/17: 7:30-9pm An Evening of Creative Inquiry in Music, Recital Hall

5. Upcoming Events

  - 2/18 Visual Acuity Work Session, 503 Moore, 1:30-3:30pm
  - 2/21 Julia Present [@Palmer2005-qb]
  - 2/28 Dr. Gilmore Present [@Page2021-dn]

6. Homework
  - READ: [@Palmer2005-qb]
  - [CITI Training](https://gilmore-lab.github.io/protocols/training.html#citi-training) ASAP - Gavin, Megan
  - [Clery Act Training](https://gilmore-lab.github.io/protocols/training.html#clery-act-training) by 2/14 - Bruna, Brianna, Nicole, Julia, Paige, Megan, Gavin
  - [Reporting Suspected Child Abuse](https://gilmore-lab.github.io/protocols/training.html#reporting-suspected-child-abuse) by 2/18 - Bruna, Brianna, Nicole, Julia, Paige, Megan
  - [Values, Ethics, & Compliance Training](https://gilmore-lab.github.io/protocols/training.html#values-ethics-and-compliance-training) by 2/18 - Bruna, Brianna, Nicole, Julia, Paige, Megan, Bri
  - [Title IX Training](https://gilmore-lab.github.io/protocols/training.html#understanding-title-ix-at-penn-state) by 2/21 - Bruna, Brianna, Nicole, Julia, Paige, Megan, Bri

### Friday, February 7, 2025

0. Attending
1. Visual Acuity Project

  - Review [New Protocol](https://docs.google.com/document/d/1qxU5-iTeqzOXE7BhoANQ5TL8xP0ofWwp2ujYLmYKUE4/edit?tab=t.0)
  - Schedule work sessions 
    - 2/11/2025 1:30-3:30pm 503 Moore

2. Upcoming Talks ~15 min 

  - 2/14: Paige Present [@Thunstedt2022-qa] 
  - 2/21: Julia Present 
  
3. Upcoming Meetings

- Visual Acuity: Mondays 12:00-1:00 in 503 Moore 
- PLAY: Mondays 2:30-3:30 in 503 Moore 
- Working Session - Visual Acuity: Tuesdays 1:30-3:30 in 503 Moore

4. Homework

  - Accept invitation to [DataCamp](https://www.datacamp.com/) sent to your PSU email address.
  - Read and prepare to discuss [@Thunstedt2022-qa] for 2/14.
  - [CITI Training](https://gilmore-lab.github.io/protocols/training.html#citi-training) ASAP - Bri, Gavin, Megan
  - [Clery Act Training](https://gilmore-lab.github.io/protocols/training.html#clery-act-training) by 2/14 - Bruna, Brianna, Nicole, Julia, Paige, Megan, Gavin, Bri

### Friday, January 31, 2025
0. Attending: Rick, Kassandra, Nicole, Paige, Brianna, Trinity, Hayley, Bri, Lina
 
1. Trinity present [Freud, S., (1913). Further recommendations in the technique of psycho-analysis. In Stachey, J., & Freud, A., (Eds.), The Standard Edition of the Complete Psychological Works of Sigmund Freud, (Vol. XII., pp. 164-191).](/lab-mtg-talks/freud-further-recommendation.pdf) 
  - Interesting further reading: [Freud, Sigmund. 1997. The Interpretation of Dreams. Translated by A. A. Brill. Wordsworth Classics of World Literature. Herts, UK: Wordsworth Editions.](https://www.amazon.com/Interpretation-Dreams-Wordsworth-Classics-Literature/dp/1853264849)

Weekly Project Meetings

- Visual Acuity: Mondays 12:00-1:00 in 503 Moore 
- PLAY: Mondays 2:30-3:30 in 503 Moore

Upcoming Talks ~15 min 

  - 2/7: Paige present 
  - 2/14: Julia present 
  
To Do:

- Please complete [CITI Training](https://gilmore-lab.github.io/protocols/training.html#citi-training) ASAP
  - Bri, Gavin, Megan
- Please complete [Clery Act Training](https://gilmore-lab.github.io/protocols/training.html#clery-act-training) by 2/7
  - Bruna, Brianna, Nicole, Julia, Paige, Megan, Gavin, Bri
- Please complete [Building a Safe Penn State: Reporting Child Abuse Training](https://gilmore-lab.github.io/protocols/training.html#building-a-safe-penn-state-reporting-child-abuse) by 2/7
  - Bruna, Brianna, Nicole, Julia, Paige, Megan, Bri


### Friday, January 24, 2025

0. Attending
1. Introductions
2. Spring 2025 Lab Priorities (Rick)
  - Play & Learning Across a Year (PLAY) Project, [PLAY site](https://play-project.org), [Parent site](https://anhourinthelife.org), [KoBoToolbox Surveys](https://PLAY-behaviorome.github.io/KoBoToolbox/)
    - Data Collection Update (Paige, Brianna)
  - [Visual Acuity](https://gilmore-lab.github.io/visual-acuity/) Project
    - [Visual Acuity Analysis Procedure](https://docs.google.com/document/d/1jdoIzE1cLHphA9y89jyhK20lTXJ2WCu4fBIATH25EeY/edit?tab=t.0)
    - [Legacy Project Acuity Data: By Paper](https://docs.google.com/spreadsheets/d/1UFZkbh9oU4JHpYsrkDQcNmDyqD4J-qB74dhyMzIkqKs/edit?gid=432255138#gid=432255138)
    - [Legacy Project Data Analysis](https://docs.google.com/spreadsheets/d/1XnGweqEAiTlU8mhvWqtCCMNm9l5txdR0YpQsuMxvgio/edit?gid=998401983#gid=998401983)
  - [Databrary](https://databrary.org), especially the [Databrary Guide](https://databrary.github.io/guide), the [*databraryr* package](https://databrary.github.io/databraryr), and the [Databrary Analytics](https://databrary.github.io/analytics).
  - Refreshing internal resources, especially the [lab website](https://gilmore-lab.github.io) and our lab [protocols site](https://gilmore-lab.github.io/protocols).
  - [Datacamp](https://www.datacamp.com/) 
3. Continue working on required training:  [Instructions](https://gilmore-lab.github.io/protocols/trainings.html)

Scheduled Weekly Project Meetings

  - Visual Acuity: Mondays 1:30-2:30 in 503 Moore
  - PLAY: Mondays 2:30-3:30 in 503 Moore

Upcoming Talks ~15 min  

  - 1/31: Trinity present - Freud
  - 2/7: Paige present
  - 2/14: Julia present - Neurogenetics