# Resources

## Lab Resources

[New Lab Member Instructions](http://gilmore-lab.github.io/protocols/onboarding.html)  

We use [Paperpile](https://paperpile.com/) for reference management. Please use the [Paperpile Instructions](http://gilmore-lab.github.io/protocols/paperpile_instructions.html) to utilize this web based reference management system.  

### Using R  

- [R for Data Science](https://r4ds.had.co.nz/)
  
### Making QR codes

The following code generates a QR code for the PLAY Project parent site and saves it to `images/play-recruiting.svg`.

```{r}
code <- qrcode::qr_code("https://www.anhourinthelife.org")
plot(code)

qr_code_svg <- qrcode::generate_svg(code, filename = "images/play-recruiting.svg")
print(qr_code_svg) # Opens in separate browser
```

## Current Projects

### Play & Learning Across a Year (PLAY) Project 
- [PLAY site](https://play-project.org) 
- [Parent site](https://anhourinthelife.org) 
- [KoBoToolbox Surveys](https://PLAY-behaviorome.github.io/KoBoToolbox/) 

The Brain and Behavioral Dynamics Lab is a [Data Collection](https://play-project.org/collection.html) and a [Data Coding](https://play-project.org/coding.html) site for the PLAY Project

### Legacy Project
- [Visual Acuity](https://gilmore-lab.github.io/visual-acuity/)

## Past Projects

#### Motion Coherence (MOCO)   
  - Infant High Density EEG Data  
    - [GitHub](https://github.com/gilmore-lab/moco)  
    - [Databrary](https://nyu.databrary.org/volume/146)   
  - Child Behavioral Data  
    - [GitHub](https://github.com/gilmore-lab/moco-psychophysics/tree/master/child-laminar-radial)  
    - [Databrary](https://nyu.databrary.org/volume/218)  
  - Adult Behavioral Data  
    - [GitHub](https://github.com/gilmore-lab/moco-psychophysics/tree/master/adult-laminar-radial)  
    - [Databrary](https://nyu.databrary.org/volume/73)    

#### Motion Form (MOFO)  
  - Child High Density EEG Data
    - [GitHub](https://github.com/gilmore-lab/child-motion-form)  
    - [Databrary](https://nyu.databrary.org/volume/144)  
  
#### Size Matters 
 - Data
    - [GitHub](https://github.com/gilmore-lab/brain-behavior-data)

#### Symmetry 
  - Adult Behavorial Data  
    - [GitHub](https://github.com/gilmore-lab/symmetry-sorting)  
    - [Databrary](https://nyu.databrary.org/volume/324)  






